var _typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};
!function t(c,d,a){function e(g,k){if(!d[g]){if(!c[g]){var h="function"==typeof require&&require;if(!k&&h)return h(g,!0);if(f)return f(g,!0);k=Error("Cannot find module '"+g+"'");throw k.code="MODULE_NOT_FOUND",k;}k=d[g]={exports:{}};c[g][0].call(k.exports,function(a){var f=c[g][1][a];return e(f?f:a)},k,k.exports,t,c,d,a)}return d[g].exports}for(var f="function"==typeof require&&require,g=0;g<a.length;g++)e(a[g]);return e}({1:[function(c,d,a){var b=c("./util.coffee");var e=c("./config/app.coffee");
d.exports=function(){function a(){}var c;return c=e.trustvoxHost+"/widget/shelf/v2",a.get=function(a,e,f){var d,g,h;return d=this._newCallback(e.codes),e=b.extend(e,{callback:d}),h=b.buildURI(c+"/"+a,e),g=document.createElement("script"),g.type="text/javascript",g.src=h,window[d]=function(a){return function(b){return f(b),a._destroyCallback(d,g)}}(this),document.getElementsByTagName("head")[0].appendChild(g)},a._newCallback=function(a){return a.join(""),this._registerCallback("_tsRatesReady"),"_tsRatesReady"},
a._destroyCallback=function(a,b){if(this._deregisterCallback(a),0===window.tsCallbacks[a])return b.parentNode.removeChild(b),window[a]=void 0},a._registerCallback=function(a){var b;return window.tsCallbacks||(window.tsCallbacks={}),(b=window.tsCallbacks)[a]||(b[a]=0),window.tsCallbacks[a]+=1,!0},a._deregisterCallback=function(a){return--window.tsCallbacks[a],!0},a}()},{"./config/app.coffee":3,"./util.coffee":12}],2:[function(c,d,a){var b=c("./products.coffee");var e=c("./api.coffee");d.exports=function(){function a(a,
e){this.storeId=a;this.products=new b(e)}return a.prototype.fillRates=function(){var a;if(a=this.products.fetchAllCodes(),0<a.length)return e.get("products_rates",{codes:a,store_id:this.storeId},function(a){return function(b){return a.products.attachRates(b.products_rates,b.features)}}(this))},a.prototype.fillComponents=function(){return this.fillRates()},a}()},{"./api.coffee":1,"./products.coffee":8}],3:[function(c,d,a){var b=[].slice;var e=c("./production.coffee");var f=c("./staging.coffee");a=
c("./dev.coffee");var g=c("./test-with-staging.coffee");c=c("../util.coffee");d.exports=c.extend(function(){var a,e;var c=arguments[0];var f=2<=arguments.length?b.call(arguments,1):[];var d=0;for(e=f.length;d<e;d++){var g=f[d];for(a in g){var ha=g[a];c[a]=ha}}return c},e,f,g,a)},{"../util.coffee":12,"./dev.coffee":15,"./production.coffee":4,"./staging.coffee":15,"./test-with-staging.coffee":15}],4:[function(c,d,a){d.exports={environment:"production",assetHost:"//rate.trustvox.com.br",trustvoxHost:"//trustvox.com.br"}},
{}],5:[function(c,d,a){d.exports=function(){function a(a,b){this.selector=a;this.watchSubtree=b}var e,c,d,h;return a.prototype.listen=function(a){var b;var c=document.querySelectorAll(this.selector);var f=[];var d=0;for(b=c.length;d<b;d++){var g=c[d];f.push(e(g,a,this.watchSubtree))}return f},c=function(a,b){return d(a,"appendChild",b),d(a,"insertBefore",b)},h=function(a,b,e){return null==e&&(e=!1),(new MutationObserver(b)).observe(a,{childList:!0,subtree:e})},d=function(a,b,e){var c;return c=a[""+
b],a[""+b]=function(){var a;return a=c.apply(this,arguments),setTimeout(e,1),a}},e="undefined"!=typeof MutationObserver&&null!==MutationObserver?h:c,a}()},{}],6:[function(c,d,a){d.exports=function(){function a(){}return a.addEvent=function(a){var b,e;return b=document.getElementById("ts-js-shelf-"+a.product_code),e=function(b){return function(){return b.sendEvent(a)}}(this),b.addEventListener?b.addEventListener("click",e):b.attachEvent("onclick",e)},a.sendEvent=function(a){var b,e;if(b="Produto: "+
a.product_name,"function"==typeof ga&&(e=ga.getAll(),0<e.length?ga(function(){return e.forEach(function(a){return ga(a.get("name")+".send","event","Trustvox <> Prateleira","Clicou nas estrelas",b)})}):ga("send","event","Trustvox <> Prateleira","Clicou nas estrelas",b)),"undefined"!=typeof _gat&&"undefined"!=typeof _gat._getTrackers)return _.each(_gat._getTrackers(),function(a){return a._trackEvent("Trustvox <> Prateleira","Clicou nas estrelas",b)})},a}()},{}],7:[function(c,d,a){d.exports=function(){function a(){}
return a.prototype.all=function(){var a,b,c;return b=function(){var b=this.fetchJs();var e=[];for(a in b)e.push(a);return e}.call(this),c=function(){var b=this.fetchNormal();var e=[];for(a in b)e.push(a);return e}.call(this),c.concat(b)},a.prototype.containers=function(a){return this.fetchNormal()[a]||this.fetchJs()[a]||[]},a.prototype.fetchJs=function(){var a;var b=document.querySelectorAll("[data-trustvox-product-code-js]");var c={};var d=this.removeFullContainers(b);var k=0;for(a=d.length;k<a;k++){var l=
d[k];b=eval(l.getAttribute("data-trustvox-product-code-js"));c[b]||(c[b]=[]);c[b]=c[b].concat(l)}return c},a.prototype.fetchNormal=function(){var a;var b=document.querySelectorAll("[data-trustvox-product-code]");var c={};var d=this.removeFullContainers(b);var k=0;for(a=d.length;k<a;k++){var l=d[k];b=l.getAttribute("data-trustvox-product-code");c[b]||(c[b]=[]);c[b]=c[b].concat(l)}return c},a.prototype.removeFullContainers=function(a){var b;var c=[];var e=0;for(b=a.length;e<b;e++){var d=a[e];0< !d.childNodes.length&&
c.push(d)}return c},a}()},{}],8:[function(c,d,a){var b=c("./product-codes.coffee");var e=c("./google-analytics.coffee");var f=c("./templates/rate.coffee");var g=c("./templates/rate-with-schema.coffee");d.exports=function(){function a(a){this.minimumOpinionsToShow=a;this.productCodes=new b}var c;return a.prototype.attachRates=function(a,b){var d,f,g,h;var k=null!=b?b.hide_empty:void 0;var l=[];b=0;for(g=a.length;b<g;b++){var m=a[b];var da=this.productCodes.containers(m.product_code);l.push(function(){var a;
var b=[];var g=0;for(a=da.length;g<a&&(d=da[g],!this._dontRender(k,m,d));g++)this._shouldSkipFilter(d)||m.count>=this.minimumOpinionsToShow||this._emptyRate(m),f=this._shouldDisplaySchema(d),h=c(m,f),d.insertAdjacentHTML("beforeEnd",h),b.push(e.addEvent(m));return b}.call(this))}return l},c=function(a,b){return b?g(a):f(a)},a.prototype.fetchAllCodes=function(){return this.productCodes.all()},a.prototype._dontRender=function(a,b,c){return!!a&&!this._shouldSkipFilter(c)&&!this._hasMinimumOpinions(b)},
a.prototype._shouldSkipFilter=function(a){return this._isTrue(a,"trustvox-should-skip-filter")},a.prototype._shouldDisplaySchema=function(a){return this._isTrue(a,"trustvox-display-rate-schema")},a.prototype._isTrue=function(a,b){return"true"===a.getAttribute("data-"+b)},a.prototype._hasMinimumOpinions=function(a){return 0!==a.count&&(!this.minimumOpinionsToShow||a.count>=this.minimumOpinionsToShow)},a.prototype._emptyRate=function(a){if(2>=a.count&&2>=a.average)return a.average=0,a.count=0},a}()},
{"./google-analytics.coffee":6,"./product-codes.coffee":7,"./templates/rate-with-schema.coffee":10,"./templates/rate.coffee":11}],9:[function(c,d,a){var b=c("./config/app.coffee");new (function(){return function(){var a=document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href=b.assetHost+"/widget.css";document.getElementsByTagName("head")[0].appendChild(a)}}())},{"./config/app.coffee":3}],10:[function(c,d,a){var b=c("../view-helpers.coffee");d.exports=function(a){return'<div class="ts-shelf-container" id="ts-js-shelf-'+
a.product_code+'">\n  <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">\n    <span class=\'ts-shelf-left ts-shelf-rate-value ts-shelf-rate-count '+b.rateCountColor(a.average)+"'>\n      <span itemprop='ratingValue'>"+a.average+' </span> de <span itemprop=\'bestRating\'>5</span>\n    </span>\n    <div class="ts-shelf-rate ts-sprite">\n      <meta content="0" itemprop="worstRating" />\n      <div class="ts-shelf-rate-symbols ts-sprite" style="width: '+b.toPercentage(a.average)+
'%;"></div>\n    </div>\n    <span class="ts-shelf-right ts-shelf-rate-count '+b.rateCountColor(a.average)+'">\n      (<span itemprop="ratingCount">'+a.count+"</span>)\n    </span>\n  </div>\n</div>"}},{"../view-helpers.coffee":13}],11:[function(c,d,a){var b=c("../view-helpers.coffee");d.exports=function(a){return'<div class="ts-shelf-container" id="ts-js-shelf-'+a.product_code+'">\n  <div>\n    <div class="ts-shelf-rate ts-sprite">\n      <div class="ts-shelf-rate-symbols ts-sprite" style="width: '+
b.toPercentage(a.average)+'%;"></div>\n    </div>\n    <span class="ts-shelf-right ts-shelf-rate-count '+b.rateCountColor(a.average)+'">\n      (<span>'+a.count+"</span>)\n    </span>\n  </div>\n</div>"}},{"../view-helpers.coffee":13}],12:[function(c,d,a){var b=[].slice;d.exports=function(){function a(){}return a.isArray=Array.isArray||function(a){return"[object Array]"==={}.toString.call(a)},a.extend=function(){var a,c;var d=arguments[0];var e=2<=arguments.length?b.call(arguments,1):[];var l=0;for(c=
e.length;l<c;l++){var m=e[l];for(a in m){var v=m[a];d[a]=v}}return d},a.buildURI=function(a,b){var c,d,e,f,g;return e=function(){var a=[];for(d in b)g=b[d],this.isArray(g)?a.push(function(){var a;var b=[];var e=0;for(a=g.length;e<a;e++)c=g[e],b.push(d+"[]="+c);return b}().join("&")):a.push(d+"="+g);return a}.call(this),f=e.join("&"),a=a+"?"+f},a}()},{}],13:[function(c,d,a){d.exports=function(){function a(){}return a.toPercentage=function(a,b){var c;return c=a/5*100,Math.round(100*c)/100},a.rateCountColor=
function(a){return 0<a?"ts-shelf-rate-enabled":"ts-shelf-rate-disabled"},a}()},{}],14:[function(c,d,a){(function(a){var b=c("domready");var d=c("./application.coffee");var g=c("./dom-change-event.coffee");c("./stylesheet-loader.coffee");b(function(){var b,c,e,f,v,n;if(_trustvox_shelf_rate)return e=function(){var a;var b=[];var d=0;for(a=_trustvox_shelf_rate.length;d<a;d++)c=_trustvox_shelf_rate[d],"_minimumOpinionsToShow"===c[0]&&b.push(c[1]);return b}()[0],v=function(){var a;var b=[];var d=0;for(a=
_trustvox_shelf_rate.length;d<a;d++)c=_trustvox_shelf_rate[d],"_storeId"===c[0]&&b.push(c[1]);return b}()[0],f=function(){var a;var b=[];var d=0;for(a=_trustvox_shelf_rate.length;d<a;d++)c=_trustvox_shelf_rate[d],"_productContainer"===c[0]&&b.push(c[1]);return b}()[0],n=function(){var a;var b=[];var d=0;for(a=_trustvox_shelf_rate.length;d<a;d++)c=_trustvox_shelf_rate[d],"_watchSubtree"===c[0]&&b.push(c[1]);return b}()[0],b=new d(v,e),b.fillComponents(),(new g(f,n)).listen(function(){return b.fillComponents()}),
a.TrustvoxRatesWidget=b})}).call(this,"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{"./application.coffee":2,"./dom-change-event.coffee":5,"./stylesheet-loader.coffee":9,domready:16}],15:[function(c,d,a){},{}],16:[function(c,d,a){!function(a,c){"undefined"!=typeof d?d.exports=c():"function"==typeof define&&"object"==_typeof(define.amd)?define(c):this[a]=c()}("domready",function(a){function b(a){for(m=1;a=d.shift();)a()}var c,d=[],h=document,
k=h.documentElement,l=k.doScroll,m=(l?/^loaded|^c/:/^loaded|c/).test(h.readyState);return h.addEventListener&&h.addEventListener("DOMContentLoaded",c=function(){h.removeEventListener("DOMContentLoaded",c,!1);b()},!1),l&&h.attachEvent("onreadystatechange",c=function(){/^c/.test(h.readyState)&&(h.detachEvent("onreadystatechange",c),b())}),a=l?function(b){self!=top?m?b():d.push(b):function(){try{k.doScroll("left")}catch(n){return setTimeout(function(){a(b)},50)}b()}()}:function(a){m?a():d.push(a)}})},
{}]},{},[14]);"use strict";var roiHeroComponents=roiHeroComponents||{};roiHeroComponents.util=roiHeroComponents.util||{};roiHeroComponents.util.removeDuplicatesFromArray=function(c){for(var d=[],a=0;a<c.length;a++)d.includes(c[a])||d.push(c[a]);return d};roiHeroComponents.util.getCookie=function(c){c=("; "+document.cookie).split("; "+c+"=");if(2==c.length)return c.pop().split(";").shift()};
roiHeroComponents.util.BRLToFloat=function(c){"string"===typeof c&&(c=c.toLocaleLowerCase(),c=c.replace("r$",""),c=c.replace("$",""),c=c.replace(",","."),c=c.trim());return parseFloat(c)};
roiHeroComponents.util.numberToBRL=function(c){var d=window.currencyCli?window.currencyCli:"R$",a=/\.?(\d{1,2})$/g,b=/(\d)(?=(\d{3})+(?!\d))/g;c?("string"===typeof c&&(c=parseFloat(c)),c=c.toFixed(2),"R$"===d?(c=c.replace(a,",$1"),c=c.replace(b,"$1.")):(c=c.replace(a,".$1"),c=c.replace(b,"$1,"))):c="R$"===d?"0,00":"0.00";return d+" "+c};
var tns=function(){function c(){for(var a,b,c,d=arguments[0]||{},e=1,f=arguments.length;e<f;e++)if(null!==(a=arguments[e]))for(b in a)c=a[b],d!==c&&void 0!==c&&(d[b]=c);return d}function d(a){return 0<=["true","false"].indexOf(a)?JSON.parse(a):a}function a(a,b,c,d){d&&a.setItem(b,c);return c}function b(){var a=window.tnsId;window.tnsId=a?a+1:1;return"tns"+window.tnsId}function e(){var a=document,b=a.body;b||(b=a.createElement("body"),b.fake=!0);return b}function f(a){var b="";a.fake&&(b=Sa.style.overflow,
a.style.background="",a.style.overflow=Sa.style.overflow="hidden",Sa.appendChild(a));return b}function g(a,b){a.fake&&(a.remove(),Sa.style.overflow=b,Sa.offsetHeight)}function h(){var a=document,b=e(),c=f(b);a=a.createElement("div");var d=!1;b.appendChild(a);try{for(var h=["calc(10px * 10)","-moz-calc(10px * 10)","-webkit-calc(10px * 10)"],k,l=0;3>l;l++)if(k=h[l],a.style.width=k,100===a.offsetWidth){d=k.replace("(10px * 10)","");break}}catch(Qd){}b.fake?g(b,c):a.remove();return d}function k(){var a=
document,b=e(),c=f(b),d=a.createElement("div");a=a.createElement("div");var h="";d.className="tns-t-subp2";a.className="tns-t-ct";for(var k=0;70>k;k++)h+="<div></div>";a.innerHTML=h;d.appendChild(a);b.appendChild(d);a=2>Math.abs(d.getBoundingClientRect().left-a.children[67].getBoundingClientRect().left);b.fake?g(b,c):d.remove();return a}function l(){var a=document,b=e(),c=f(b),d=a.createElement("div"),h=a.createElement("style");h.type="text/css";d.className="tns-mq-test";b.appendChild(h);b.appendChild(d);
h.styleSheet?h.styleSheet.cssText="@media all and (min-width:1px){.tns-mq-test{position:absolute}}":h.appendChild(a.createTextNode("@media all and (min-width:1px){.tns-mq-test{position:absolute}}"));a=window.getComputedStyle?window.getComputedStyle(d).position:d.currentStyle.position;b.fake?g(b,c):d.remove();return"absolute"===a}function m(a){var b=document.createElement("style");a&&b.setAttribute("media",a);document.querySelector("head").appendChild(b);return b.sheet?b.sheet:b.styleSheet}function v(a,
b,c,d){"insertRule"in a?a.insertRule(b+"{"+c+"}",d):a.addRule(b,c,d)}function n(a){return("insertRule"in a?a.cssRules:a.rules).length}function ha(a,b,c){for(var d=0,e=a.length;d<e;d++)b.call(c,a[d],d)}function Y(a,b){a="undefined"!==typeof a.item||a instanceof Array?a:[a];if("[object Object]"===Object.prototype.toString.call(b))for(var c=a.length;c--;)for(var d in b)a[c].setAttribute(d,b[d])}function za(a,b){a="undefined"!==typeof a.item||a instanceof Array?a:[a];b=b instanceof Array?b:[b];for(var c=
b.length,d=a.length;d--;)for(var e=c;e--;)a[d].removeAttribute(b[e])}function ic(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b}function ka(a,b){"none"!==a.style.display&&(a.style.display="none")}function da(a,b){"none"===a.style.display&&(a.style.display="")}function lb(a){if("string"===typeof a){var b=[a],c=a.charAt(0).toUpperCase()+a.substr(1);["Webkit","Moz","ms","O"].forEach(function(d){"ms"===d&&"transform"!==a||b.push(d+c)});a=b}for(var d=document.createElement("fakeelement"),
e=0;e<a.length;e++){var f=a[e];if(void 0!==d.style[f])return f}return!1}function Dd(a){if(!a||!window.getComputedStyle)return!1;var b=document,c=e(),d=f(c);b=b.createElement("p");var h=9<a.length?"-"+a.slice(0,-9).toLowerCase()+"-":"";h+="transform";c.insertBefore(b,null);b.style[a]="translate3d(1px,1px,1px)";a=window.getComputedStyle(b).getPropertyValue(h);c.fake?g(c,d):b.remove();return void 0!==a&&0<a.length&&"none"!==a}function Pc(a,b){var c=!1;/^Webkit/.test(a)?c="webkit"+b+"End":/^O/.test(a)?
c="o"+b+"End":a&&(c=b.toLowerCase()+"end");return c}function N(a,b){for(var c in b)a.addEventListener(c,b[c],"touchstart"===c||"touchmove"===c?mb:!1)}function S(a,b){for(var c in b){var d=0<=["touchstart","touchmove"].indexOf(c)?mb:!1;a.removeEventListener(c,b[c],d)}}function Fd(){return{topics:{},on:function(a,b){this.topics[a]=this.topics[a]||[];this.topics[a].push(b)},off:function(a,b){if(this.topics[a])for(var c=0;c<this.topics[a].length;c++)if(this.topics[a][c]===b){this.topics[a].splice(c,1);
break}},emit:function(a,b){this.topics[a]&&this.topics[a].forEach(function(a){a(b)})}}}function Gd(a,b,c,d,e,f,g){function h(){f-=k;n+=m;a.style[b]=c+n+l+d;0<f?setTimeout(h,k):g()}var k=Math.min(f,10),l=0<=e.indexOf("%")?"%":"px";e=e.replace(l,"");var n=Number(a.style[b].replace(c,"").replace(d,"").replace(l,"")),m=(e-n)/f*k;setTimeout(h,k)}var la=window,Ta=la.requestAnimationFrame||la.webkitRequestAnimationFrame||la.mozRequestAnimationFrame||la.msRequestAnimationFrame||function(a){return setTimeout(a,
16)};la=window;var kc=la.cancelAnimationFrame||la.mozCancelAnimationFrame||function(a){clearTimeout(a)},Sa=document.documentElement,Ua=(la="classList"in document.createElement("_"))?function(a,b){return a.classList.contains(b)}:function(a,b){return 0<=a.className.indexOf(b)},T=la?function(a,b){Ua(a,b)||a.classList.add(b)}:function(a,b){Ua(a,b)||(a.className+=" "+b)},ma=la?function(a,b){Ua(a,b)&&a.classList.remove(b)}:function(a,b){Ua(a,b)&&(a.className=a.className.replace(b,""))},nb=!1;try{var lc=
Object.defineProperty({},"passive",{get:function(){nb=!0}});window.addEventListener("test",null,lc)}catch(Pd){}var mb=nb?{passive:!0}:!1;Object.keys||(Object.keys=function(a){var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b});"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)});return function Ed(e){function f(a){for(var b in a)r||("slideBy"===b&&(a[b]="page"),"edgePadding"===b&&(a[b]=!1),"autoHeight"===
b&&(a[b]=!1)),"outer"===Ga&&"autoHeight"===b&&(a[b]=!0),"responsive"===b&&f(a[b])}function g(a){a&&(ua=va=Ha=Ia=Ja=ia=Ka=La=!1)}function la(a){a=a?Math.max(0,Math.min(Z?u-1:u-A,a)):0;return r?a+U:a}function cb(a){null==a&&(a=p);for(r&&(a-=U);0>a;)a+=u;return Math.floor(a%u)}function Sa(){if(B||y&&!mc)var a=u-1;else{a=y?"fixedWidth":"items";var b=[];(y||e[a]<u)&&b.push(e[a]);if(E)for(var c in E){var d=E[c][a];d&&(y||d<u)&&b.push(d)}b.length||b.push(0);a=Math.ceil(y?mc/Math.min.apply(null,b):Math.max.apply(null,
b))}b=r?Math.ceil((5*a-u)/2):4*a-u;b=Math.max(a,b);return Fa("edgePadding")?b+1:b}function jc(a){return a.clientWidth||jc(a.parentNode)}function Fa(a){if(e[a])return!0;if(E)for(var b in E)if(E[b][a])return!0;return!1}function w(a,b){null==b&&(b=Nb);if("items"===a&&y)return Math.floor(ta/(y+H))||1;var c=e[a];if(E)for(var d in E)b>=parseInt(d)&&a in E[d]&&(c=E[d][a]);"slideBy"===a&&"page"===c&&(c=w("items"));r||"slideBy"!==a&&"items"!==a||(c=Math.floor(c));return c}function Lb(a,b,c,e){var d="";a?(c=
a,b&&(c-=b),d=C?"margin: 0 "+c+"px 0 "+a+"px;":"margin: "+a+"px 0 "+c+"px 0;"):b&&!c&&(a="-"+b+"px",d="margin: 0 "+(C?a+" 0 0":"0 "+a+" 0")+";");F&&e&&(d+=ob(e));return d}function Ob(a,b,c){return a?(a+b)*D+"px":Va?Va+"("+100*D+"% / "+c+")":100*D/c+"%"}function Pb(a,b,c){a?a=a+b+"px":(r||(c=Math.floor(c)),a=r?D:c,a=Va?Va+"(100% / "+a+")":100/a+"%");a="width:"+a;return"inner"!==Ga?a+";":a+" !important;"}function Qb(a){var b="";!1!==a&&(b=(C?"padding-":"margin-")+(C?"right":"bottom")+": "+a+"px;");
return b}function mb(a,b){(a=a.substring(0,a.length-b).toLowerCase())&&(a="-"+a+"-");return a}function ob(a){return mb(F,18)+"transition-duration:"+a/1E3+"s;"}function nb(a){return mb(Rb,17)+"animation-duration:"+a/1E3+"s;"}function Qc(){if(Fa("autoHeight")||B||!C){var a=q.querySelectorAll("img");ha(a,function(a){var b=a.src;0>b.indexOf("data:image")?(N(a,nc),a.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==",a.src=b):T(a,Sb)});Ta(function(){oc(ic(a),function(){function a(){if(!C||
B)Rc(),B?(db=pc(),Tb&&(oa=qc()),pa=pb(),g(ja||oa)):rc();r&&qb();Sc();Tc()}sc=!0;if(B){var b=Z?p:u-1;(function Hd(){z[b-1].getBoundingClientRect().right.toFixed(2)===z[b].getBoundingClientRect().left.toFixed(2)?a():setTimeout(function(){Hd()},16)})()}else a()})})}else r&&qb(),Sc(),Tc()}function lc(){for(var a=p,b=p+Math.min(u,A);a<b;a++){var c=z[a];Y(c,{"aria-hidden":"false"});za(c,["tabindex"]);T(c,rb);r||(c.style.left=100*(a-p)/A+"%",T(c,Ma),ma(c,wa))}r&&C&&(Uc||B?(v(G,"#"+V+" > .tns-item","font-size:"+
qa.getComputedStyle(z[0]).fontSize+";",n(G)),v(G,"#"+V,"font-size:0;",n(G))):ha(z,function(a,b){a.style.marginLeft=Va?Va+"("+100*b+"% / "+D+")":100*b/D+"%"}));eb?(b=Lb(e.edgePadding,e.gutter,e.fixedWidth,e.speed),v(G,"#"+V+"-iw",b,n(G)),r&&(b=C&&!B?"width:"+Ob(e.fixedWidth,e.gutter,e.items)+";":"",F&&(b+=ob(xa)),v(G,"#"+V,b,n(G))),b=C&&!B?Pb(e.fixedWidth,e.gutter,e.items):"",e.gutter&&(b+=Qb(e.gutter)),r||(F&&(b+=ob(xa)),Rb&&(b+=nb(xa)))):(aa.style.cssText=Lb(ba,H,y),r&&C&&!B&&(q.style.width=Ob(y,
H,A)),b=C&&!B?Pb(y,H,A):"",H&&(b+=Qb(H)));b&&v(G,"#"+V+" > .tns-item",b,n(G));if(E&&eb)for(var d in E){d=parseInt(d);a=E[d];var f=c=b=b="",g=B?null:w("items",d),h=w("fixedWidth",d),k=w("speed",d),l=w("edgePadding",d),m=w("gutter",d);if("edgePadding"in a||"gutter"in a)b="#"+V+"-iw{"+Lb(l,m,h,k)+"}";r&&C&&!B&&("fixedWidth"in a||"items"in a||y&&"gutter"in a)&&(c="width:"+Ob(h,m,g)+";");F&&"speed"in a&&(c+=ob(k));c&&(c="#"+V+"{"+c+"}");if("fixedWidth"in a||y&&"gutter"in a||!r&&"items"in a)f+=Pb(h,m,g);
"gutter"in a&&(f+=Qb(m));!r&&"speed"in a&&(F&&(f+=ob(k)),Rb&&(f+=nb(k)));f&&(f="#"+V+" > .tns-item{"+f+"}");(b=b+c+f)&&G.insertRule("@media (min-width: "+d/16+"em) {"+b+"}",G.cssRules.length)}}function Sc(){if(tc){var a=ia?"stop":"start";L?Y(L,{"data-action":a}):e.autoplayButtonOutput&&(W.insertAdjacentHTML("afterbegin",'<button data-action="'+a+'" type="button">'+sb[0]+a+sb[1]+Na[0]+"</button>"),L=W.querySelector("[data-action]"));L&&N(L,{click:Vc});ia&&(Ub(),Ka&&N(q,tb),La&&N(q,ub))}if(uc){a=r?
U:0;if(ca){Y(ca,{"aria-label":"Carousel Pagination"});O=ca.children;for(var b=0;b<u;b++){var c=O[b];c&&Y(c,{"data-nav":b,tabindex:"-1","aria-selected":"false","aria-controls":z[a+b].id})}}else{c="";var d=vc?"":'style="display:none"';for(b=0;b<u;b++)c+='<button data-nav="'+b+'" tabindex="-1" aria-selected="false" aria-controls="'+z[a+b].id+'" '+d+' type="button"></button>';W.insertAdjacentHTML("afterbegin",'<div class="tns-nav" aria-label="Carousel Pagination">'+c+"</div>");ca=W.querySelector(".tns-nav");
O=ca.children}wc();F&&(a=F.substring(0,F.length-18).toLowerCase(),b="transition: all "+xa/1E3+"s",a&&(b="-"+a+"-"+b),v(G,"[aria-controls^="+V+"-item]",b,n(G)));Y(O[Aa],{tabindex:"0","aria-selected":"true"});T(O[Aa],Vb);N(ca,xc)}Wb&&(I||J&&K?(I&&(J=I.children[0],K=I.children[1],Y(I,{"aria-label":"Carousel Navigation",tabindex:"0"}),Y(I.children,{"aria-controls":V,tabindex:"-1"})),Y(J,{"data-controls":"prev"}),Y(K,{"data-controls":"next"})):(W.insertAdjacentHTML("afterbegin",'<div class="tns-controls" aria-label="Carousel Navigation" tabindex="0"><button data-controls="prev" tabindex="-1" aria-controls="'+
V+'" type="button">'+Oa[0]+'</button><button data-controls="next" tabindex="-1" aria-controls="'+V+'" type="button">'+Oa[1]+"</button></div>"),I=W.querySelector(".tns-controls"),J=I.children[0],K=I.children[1]),vb="button"===J.nodeName.toLowerCase(),wb="button"===K.nodeName.toLowerCase(),Wc(),I?N(I,xb):(N(J,xb),N(K,xb)));yc()}function Tc(){if(r&&Wa){var a={};a[Wa]=ra;N(q,a)}Ha&&N(q,yb);Ia&&N(q,zb);Ja&&N(X,Ab);if("inner"===Ga)R.on("outerResized",function(){Xc();R.emit("innerLoaded",ea())});else(E||
y||B||sa||!C)&&N(qa,{resize:Yc});if("outer"===Ga)R.on("innerLoaded",Xb);else sa&&!ja&&Xb();Zc();ja?$c():oa&&ad();R.on("indexChanged",bd);"function"===typeof zc&&zc(ea());"inner"===Ga&&R.emit("innerLoaded",ea())}function Yc(a){Ta(function(){Xc(Ba(a))})}function Xc(a){if(Ac){"outer"===Ga&&R.emit("outerResized",ea(a));Nb=qa.innerWidth||X.documentElement.clientWidth||X.body.clientWidth;var b,c=Bb,d=!1;E&&(Bc(),(b=c!==Bb)&&R.emit("newBreakpointStart",ea(a)));var e,f=A,Mb=ja,h=oa,k=Ja,l=ua,m=va,ha=Ha,Y=
Ia,x=ia,za=Ka,ic=La;c=p;if(b){var F=y,M=sa,O=Oa;var P=Na;if(!eb)var Q=H,W=ba}Ja=w("arrowKeys");ua=w("controls");va=w("nav");Ha=w("touch");Ia=w("mouseDrag");ia=w("autoplay");Ka=w("autoplayHoverPause");La=w("autoplayResetOnVisibility");b&&(ja=w("disable"),y=w("fixedWidth"),xa=w("speed"),sa=w("autoHeight"),Oa=w("controlsText"),Na=w("autoplayText"),Cc=w("autoplayTimeout"),eb||(ba=w("edgePadding"),H=w("gutter")));g(ja);ta=jc(Yb)-(2*ba-H);C&&!B||ja||(Rc(),C||(rc(),d=!0));if(y||B)db=pc(),pa=pb();if(b||y)if(A=
w("items"),fb=w("slideBy"),e=A!==f)y||B||(pa=pb()),Dc();if(b&&ja!==Mb)if(ja)$c();else if(Cb){G.disabled=!1;q.className+=Xa;qb();if(Z)for(f=U;f--;)r&&da(z[f]),da(z[D-f-1]);if(!r)for(f=p,Mb=p+u;f<Mb;f++){var fa=z[f],ra=f<p+A?Ma:wa;fa.style.left=100*(f-p)/A+"%";T(fa,ra)}cd();Cb=!1}if(Tb&&(b||y||B)&&(oa=qc(),oa!==h))if(oa)Ec(Fc(la(0))),ad();else{if(Db){ba&&eb&&(aa.style.margin="");if(U)for(d=U;d--;)r&&ma(z[d],"tns-transparent"),ma(z[D-d-1],"tns-transparent");cd();Db=!1}d=!0}g(ja||oa);ia||(Ka=La=!1);Ja!==
k&&(Ja?N(X,Ab):S(X,Ab));ua!==l&&(ua?I?da(I):(J&&da(J),K&&da(K)):I?ka(I):(J&&ka(J),K&&ka(K)));va!==m&&(va?(da(ca),wc()):ka(ca));Ha!==ha&&(Ha?N(q,yb):S(q,yb));Ia!==Y&&(Ia?N(q,zb):S(q,zb));ia!==x&&(ia?(L&&da(L),na||gb||Ub()):(L&&ka(L),na&&Zb()));Ka!==za&&(Ka?N(q,tb):S(q,tb));La!==ic&&(La?N(X,ub):S(X,ub));b&&(y!==F&&(d=!0),sa===M||sa||(aa.style.height=""),ua&&Oa!==O&&(J.innerHTML=Oa[0],K.innerHTML=Oa[1]),L&&Na!==P&&(F=ia?1:0,M=L.innerHTML,O=M.length-P[F].length,M.substring(O)===P[F]&&(L.innerHTML=M.substring(0,
O)+Na[F])));if(P=p!==c)R.emit("indexChanged",ea()),d=!0;e&&(P||bd(),r||Jd());if(!ja&&!oa){if(b&&!eb){if(ba!==W||H!==Q)aa.style.cssText=Lb(ba,H,y);C&&(r&&(q.style.width=Ob(y,H,A)),e=Pb(y,H,A)+Qb(H),Q=G,W=n(G)-1,"deleteRule"in Q?Q.deleteRule(W):Q.removeRule(W),v(G,"#"+V+" > .tns-item",e,n(G)))}sa&&Xb();d&&(qb(),Pa=p)}b&&R.emit("newBreakpointEnd",ea(a))}}function qc(){return y||B?y?(y+H)*u<=ta+2*ba:(Z?P[u]:dd())<=ta+2*ba:u<=A}function Bc(){Bb=0;for(var a in E)a=parseInt(a),Nb>=a&&(Bb=a)}function yc(){!ia&&
L&&ka(L);!va&&ca&&ka(ca);ua||(I?ka(I):(J&&ka(J),K&&ka(K)))}function cd(){ia&&L&&da(L);va&&ca&&da(ca);ua&&(I?da(I):(J&&da(J),K&&da(K)))}function ad(){if(!Db){ba&&(aa.style.margin="0px");if(U)for(var a=U;a--;)r&&T(z[a],"tns-transparent"),T(z[D-a-1],"tns-transparent");yc();Db=!0}}function $c(){if(!Cb){G.disabled=!0;q.className=q.className.replace(Xa.substring(1),"");za(q,["style"]);if(Z)for(var a=U;a--;)r&&ka(z[a]),ka(z[D-a-1]);C&&r||za(aa,["style"]);if(!r){a=p;for(var b=p+u;a<b;a++){var c=z[a];za(c,
["style"]);ma(c,Ma);ma(c,wa)}}yc();Cb=!0}}function Zc(){if(ed&&!ja){var a=p;if(B){var b=p+1;var c=b;for(var d=P[p]+ta+ba-H;P[b]<d;)b++,c=b}else c=p+A;ba&&(--a,B||(c+=1));a=Math.floor(Math.max(a,0));for(c=Math.ceil(Math.min(c,D));a<c;a++)ha(z[a].querySelectorAll(".tns-lazy-img"),function(a){var b={};b[Wa]=function(a){a.stopPropagation()};N(a,b);if(!Ua(a,"loaded")){if(b=a.getAttribute("data-srcset"))a.srcset=b;a.src=a.getAttribute("data-src");T(a,"loaded")}})}}function fd(a){a=a.target||qa.event.srcElement;
T(a,Sb);S(a,nc)}function gd(a,b){var c=[],d=a;for(a=Math.min(a+b,D);d<a;d++)ha(z[d].querySelectorAll("img"),function(a){c.push(a)});return c}function Xb(){var a=sa?gd(p,A):gd(U,u);Ta(function(){oc(a,hd)})}function oc(a,b){if(sc)return b();a.forEach(function(b,c){Ua(b,Sb)&&a.splice(c,1)});if(!a.length)return b();Ta(function(){oc(a,b)})}function bd(){Zc();for(var a=p+Math.min(u,A),b=D;b--;){var c=z[b];b>=p&&b<a?c.hasAttribute("tabindex")&&(Y(c,{"aria-hidden":"false"}),za(c,["tabindex"]),T(c,rb)):(c.hasAttribute("tabindex")||
Y(c,{"aria-hidden":"true",tabindex:"-1"}),Ua(c,rb)&&ma(c,rb))}Wc();wc();va&&(Aa=-1!==hb?hb:cb(),hb=-1,Aa!==Eb&&(a=O[Eb],b=O[Aa],Y(a,{tabindex:"-1","aria-selected":"false"}),Y(b,{tabindex:"0","aria-selected":"true"}),ma(a,Vb),T(b,Vb),Eb=Aa))}function id(a,b){var c=[],d=a;for(a=Math.min(a+b,D);d<a;d++)c.push(z[d].offsetHeight);return Math.max.apply(null,c)}function hd(){var a=sa?id(p,A):id(U,u);aa.style.height!==a&&(aa.style.height=a+"px")}function Rc(){P=[0];for(var a=C?"left":"top",b=z[0].getBoundingClientRect()[a],
c,d=1;d<D;d++)c=z[d].getBoundingClientRect()[a],P.push(c-b)}function Jd(){for(var a=p+Math.min(u,A),b=D;b--;){var c=z[b];b>=p&&b<a?(T(c,"tns-moving"),c.style.left=100*(b-p)/A+"%",T(c,Ma),ma(c,wa)):c.style.left&&(c.style.left="",T(c,wa),ma(c,Ma));ma(c,$b)}setTimeout(function(){ha(z,function(a){ma(a,"tns-moving")})},300)}function ac(a,b,c){a?b.disabled=c:b.setAttribute("aria-disabled",c.toString())}function Wc(){if(ua&&!Fb&&!Z){var a=vb?J.disabled:"true"===J.getAttribute("aria-disabled"),b=wb?K.disabled:
"true"===K.getAttribute("aria-disabled"),c=p<=ya?!0:!1,d=!Fb&&p>=pa?!0:!1;c&&!a&&ac(vb,J,!0);!c&&a&&ac(vb,J,!1);d&&!b&&ac(wb,K,!0);!d&&b&&ac(wb,K,!1)}}function dd(){return y?(y+H)*D:P[D-1]+z[D-1].getBoundingClientRect().width}function pc(){var a=ta-(dd()-H);ba&&(a+=ba-H);0<a&&(a=0);return a}function Fc(a){null==a&&(a=p);a=C&&!B?y?-(y+H)*a:100*-a/(Gb?D:A):-P[a];jd&&(a=Math.max(a,db));return a+=!C||B||y?"px":"%"}function qb(a){F&&(q.style[F]="0s");Ec(a)}function Ec(a){null==a&&(a=Fc());q.style[Ya]=
Qa+a+Za}function kd(a,b,c,d){var e=a+A;Z||(e=Math.min(e,D));for(var f=a;f<e;f++){var g=z[f];d||(g.style.left=100*(f-p)/A+"%");Gc&&bc&&(g.style[bc]=g.style[Hc]=Gc*(f-a)/1E3+"s");ma(g,b);T(g,c);d&&ib.push(g)}}function Ic(a,b){Jc&&Dc();if(p!==Pa||b)R.emit("indexChanged",ea()),R.emit("transitionStart",ea()),sa&&Xb(),na&&a&&0<=["click","keydown"].indexOf(a.type)&&Zb(),Ra=!0,Kd()}function ra(a){if(r||Ra){R.emit("transitionEnd",ea(a));if(!r&&0<ib.length)for(var b=0;b<ib.length;b++){var c=ib[b];c.style.left=
"";Hc&&bc&&(c.style[Hc]="",c.style[bc]="");ma(c,$b);T(c,wa)}if(!a||!r&&a.target.parentNode===q||a.target===q&&a.propertyName.toLowerCase().replace(/-/g,"")===Ya.toLowerCase().replace(/-/g,""))Jc||(a=p,Dc(),p!==a&&(R.emit("indexChanged",ea()),qb())),"inner"===Ga&&R.emit("innerLoaded",ea()),Ra=!1,Pa=p}}function $a(a,b){if(!oa)if("prev"===a)Ca(b,-1);else if("next"===a)Ca(b,1);else{Ra&&ra();var c=cb(),d=0;"first"===a?d=-c:"last"===a?d=r?u-A-c:u-1-c:("number"!==typeof a&&(a=parseInt(a)),isNaN(a)||(b||
(a=Math.max(0,Math.min(u-1,a))),d=a-c));!r&&d&&Math.abs(d)<A&&(a=0<d?1:-1,d+=p+d-u>=ya?u*a:2*u*a*-1);p+=d;r&&Z&&(p<ya&&(p+=u),p>pa&&(p-=u));cb(p)!==cb(Pa)&&Ic(b)}}function Ca(a,b){Ra&&ra();if(!b){a=Ba(a);for(var c=a.target||a.srcElement;c!==I&&0>[J,K].indexOf(c);)c=c.parentNode;c=[J,K].indexOf(c);if(0<=c){var d=!0;b=0===c?-1:1}}if(Fb){if(p===ya&&-1===b){$a("last",a);return}if(p===pa&&1===b){$a("first",a);return}}b&&(p+=fb*b,B&&(p=Math.floor(p)),Ic(d||a&&"keydown"===a.type?a:null))}function Kc(){jb=
setInterval(function(){Ca(null,ld)},Cc);na=!0}function md(a,b){Y(L,{"data-action":a});L.innerHTML=sb[0]+a+sb[1]+b}function Ub(){Kc();L&&md("stop",Na[1])}function Zb(){clearInterval(jb);na=!1;L&&md("start",Na[0])}function Vc(){na?(Zb(),gb=!0):(Ub(),gb=!1)}function Ba(a){a=a||qa.event;return kb(a)?a.changedTouches[0]:a}function kb(a){return 0<=a.type.indexOf("touch")}function nd(a){Ra&&ra();ab=!0;r&&(kc(Da),Da=0);var b=Ba(a);R.emit(kb(a)?"touchStart":"dragStart",ea(a));!kb(a)&&0<=["img","a"].indexOf((a.target||
qa.event.srcElement).nodeName.toLowerCase())&&(a.preventDefault?a.preventDefault():a.returnValue=!1);fa.x=Ea.x=parseInt(b.clientX);fa.y=Ea.y=parseInt(b.clientY);r&&(cc=parseFloat(q.style[Ya].replace(Qa,"").replace(Za,"")),F&&(q.style[F]="0s"))}function od(a){if(ab){var b=Ba(a);fa.x=parseInt(b.clientX);fa.y=parseInt(b.clientY);r&&!Da&&(Da=Ta(function(){pd(a)}))}}function qd(){if("?"===bb&&fa.x!==Ea.x&&fa.y!==Ea.y){var a=!1,b=Math.abs(90-Math.abs(180/Math.PI*Math.atan2(fa.y-Ea.y,fa.x-Ea.x)));b>=90-
Hb?a="horizontal":b<=Hb&&(a="vertical");bb=a===e.axis}}function pd(a){if(bb){if(kc(Da),ab&&(Da=Ta(function(){pd(a)})),qd(),bb){try{a.type&&R.emit(kb(a)?"touchMove":"dragMove",ea(a))}catch(Rd){}var b=cc,c=Lc(fa,Ea);!C||y||B?b=b+c+"px":(b+=Gb?c*A*100/(ta*D):100*c/ta,b+="%");q.style[Ya]=Qa+b+Za}}else ab=!1}function dc(a){if(ab){r&&(kc(Da),F&&(q.style[F]=""));ab=!1;var b=Ba(a);fa.x=parseInt(b.clientX);fa.y=parseInt(b.clientY);var c=Lc(fa,Ea);if(5<=Math.abs(c)){if(!kb(a)){var d=a.target||qa.event.srcElement;
N(d,{click:function Id(a){a.preventDefault?a.preventDefault():a.returnValue=!1;S(d,{click:Id})}})}r?Da=Ta(function(){if(C&&!B){var b=-c*A/ta;b=0<c?Math.floor(b):Math.ceil(b);p+=b}else if(b=-(cc+c),0>=b)p=ya;else if(b>=P[P.length-1])p=pa;else for(var d=0;d<D&&b>=P[d];)p=d,b>P[d]&&0>c&&(p+=1),d++;Ic(a,c);R.emit(kb(a)?"touchEnd":"dragEnd",ea(a))}):(qd(),bb&&Ca(a,0<c?-1:1))}}Hb&&(bb="?")}function rc(){aa.style.height=P[p+A]-P[p]+"px"}function Ld(){Q=[];for(var a=cb()%A;a<u;)r&&!Z&&a+A>u&&(a=u-A),Q.push(a),
a+=A;(Z&&Q.length*A<u||!Z&&0<Q[0])&&Q.unshift(0)}function wc(){va&&!vc&&(Ld(),Q!==ec&&(ha(O,function(a,b){0>Q.indexOf(b)?ka(a):da(a)}),ec=Q))}function ea(a){return{container:q,slideItems:z,navContainer:ca,navItems:O,controlsContainer:I,hasControls:Wb,prevButton:J,nextButton:K,items:A,slideBy:fb,cloneCount:U,slideCount:u,slideCountNew:D,index:p,indexCached:Pa,navCurrentIndex:Aa,navCurrentIndexCached:Eb,visibleNavIndexes:Q,visibleNavIndexesCached:ec,sheet:G,event:a||{}}}e=c({container:".slider",mode:"carousel",
axis:"horizontal",items:1,gutter:0,edgePadding:0,fixedWidth:!1,autoWidth:!1,viewportMax:!1,slideBy:1,controls:!0,controlsText:["prev","next"],controlsContainer:!1,prevButton:!1,nextButton:!1,nav:!0,navContainer:!1,navAsThumbnails:!1,arrowKeys:!1,speed:300,autoplay:!1,autoplayTimeout:5E3,autoplayDirection:"forward",autoplayText:["start","stop"],autoplayHoverPause:!1,autoplayButton:!1,autoplayButtonOutput:!0,autoplayResetOnVisibility:!0,animateIn:"tns-fadeIn",animateOut:"tns-fadeOut",animateNormal:"tns-normal",
animateDelay:!1,loop:!0,rewind:!1,autoHeight:!1,responsive:!1,lazyload:!1,touch:!0,mouseDrag:!1,swipeAngle:15,nested:!1,freezable:!0,onInit:!1,useLocalStorage:!0},e||{});var X=document,qa=window,x={},M=e.useLocalStorage;if(M){var rd=navigator.userAgent,Ib=new Date;try{(x=qa.localStorage)?(x.setItem(Ib,Ib),M=x.getItem(Ib)==Ib,x.removeItem(Ib)):M=!1,M||(x={})}catch(Mb){M=!1}M&&(x.tnsApp&&x.tnsApp!==rd&&"tC tPL tMQ tTf t3D tTDu tTDe tADu tADe tTE tAE".split(" ").forEach(function(a){x.removeItem(a)}),
localStorage.tnsApp=rd)}for(var Va=x.tC?d(x.tC):a(x,"tC",h(),M),Uc=x.tPL?d(x.tPL):a(x,"tPL",k(),M),eb=x.tMQ?d(x.tMQ):a(x,"tMQ",l(),M),Gb=x.tTf?d(x.tTf):a(x,"tTf",lb("transform"),M),Md=x.t3D?d(x.t3D):a(x,"t3D",Dd(Gb),M),F=x.tTDu?d(x.tTDu):a(x,"tTDu",lb("transitionDuration"),M),bc=x.tTDe?d(x.tTDe):a(x,"tTDe",lb("transitionDelay"),M),Rb=x.tADu?d(x.tADu):a(x,"tADu",lb("animationDuration"),M),Hc=x.tADe?d(x.tADe):a(x,"tADe",lb("animationDelay"),M),Wa=x.tTE?d(x.tTE):a(x,"tTE",Pc(F,"Transition"),M),sd=x.tAE?
d(x.tAE):a(x,"tAE",Pc(Rb,"Animation"),M),td=qa.console&&"function"===typeof qa.console.warn,fc="container controlsContainer prevButton nextButton navContainer autoplayButton".split(" "),ud={},vd=fc.length;vd--;){var Jb=fc[vd];if("string"===typeof e[Jb]){var wd=e[Jb],Mc=X.querySelector(wd);ud[Jb]=wd;if(Mc&&Mc.nodeName)e[Jb]=Mc;else{td&&console.warn("Can't find",e[Jb]);return}}}if(1>e.container.children.length)td&&console.warn("No slides found in",e.container);else{var E=e.responsive,Ga=e.nested,r=
"carousel"===e.mode?!0:!1;if(E){0 in E&&(e=c(e,E[0]),delete E[0]);var Nc={},Oc;for(Oc in E){var Kb=E[Oc];Kb="number"===typeof Kb?{items:Kb}:Kb;Nc[Oc]=Kb}E=Nc;Nc=null}r&&"outer"!==Ga||f(e);if(!r){e.axis="horizontal";e.slideBy="page";e.edgePadding=!1;var Ma=e.animateIn,$b=e.animateOut,Gc=e.animateDelay,wa=e.animateNormal}var C="horizontal"===e.axis?!0:!1,W=X.createElement("div"),aa=X.createElement("div"),q=e.container,Yb=q.parentNode,xd=q.outerHTML,z=q.children,u=z.length,Bb,Nb=qa.innerWidth||X.documentElement.clientWidth||
X.body.clientWidth,Ac=!0;E&&Bc();var B=e.autoWidth,y=w("fixedWidth"),ba=w("edgePadding"),H=w("gutter"),ta=jc(Yb)-(2*ba-H),A=B?1:Math.floor(w("items")),fb=w("slideBy"),mc=e.viewportMax||e.fixedWidthViewportWidth,Ja=w("arrowKeys"),xa=w("speed"),Fb=e.rewind,Z=Fb?!1:e.loop,sa=w("autoHeight"),ua=w("controls"),Oa=w("controlsText"),va=w("nav"),Ha=w("touch"),Ia=w("mouseDrag"),ia=w("autoplay"),Cc=w("autoplayTimeout"),Na=w("autoplayText"),Ka=w("autoplayHoverPause"),La=w("autoplayResetOnVisibility"),G=m(),ed=
e.lazyload,P,ib=[],U=Z?Sa():0,D=r?u+2*U:u+U,jd=!y&&!B||Z?!1:!0,db=y?pc():null,Jc=r&&Z?!1:!0,Ya=C?"left":"top",Qa="",Za="",pb=function(){return y?function(){return Math.floor(-db/(y+H))+1}:B?function(){for(var a=D,b=a-1;a--;)P[a]>-db&&(b=a);return b}:function(){return Z||r?Math.max(0,D-Math.ceil(A)):D-1}}(),p=la(w("startIndex")),Pa=p,ya=0,pa=B?null:pb(),Hb=e.swipeAngle,bb=Hb?"?":!0,Ra=!1,zc=e.onInit,R=new Fd,Xa=" tns-slider tns-"+e.mode,V=q.id||b(),ja=w("disable"),Cb=!1,Tb=e.freezable,oa=Tb&&!B?qc():
!1,Db=!1,xb={click:Ca,keydown:function(a){a=Ba(a);switch(a.keyCode){case 37:case 38:case 33:J.disabled||Ca(a,-1);break;case 39:case 40:case 34:K.disabled||Ca(a,1);break;case 36:$a("first",a);break;case 35:$a("last",a)}}},xc={click:function(a){Ra&&ra();a=Ba(a);for(var b=a.target||a.srcElement;b!==ca&&!b.hasAttribute("data-nav");)b=b.parentNode;b.hasAttribute("data-nav")&&(b=hb=[].indexOf.call(O,b),$a(b,a))},keydown:function(a){function b(a){return e.navContainer?a:Q[a]}var c=X.activeElement;if(c.hasAttribute("data-nav")){a=
Ba(a);var d=a.keyCode;c=[].indexOf.call(O,c);var f=Q.length,g=Q.indexOf(c);e.navContainer&&(f=u,g=c);switch(d){case 37:case 33:0<g&&O[b(g-1)].focus();break;case 38:case 36:0<g&&O[b(0)].focus();break;case 39:case 34:g<f-1&&O[b(g+1)].focus();break;case 40:case 35:g<f-1&&O[b(f-1)].focus();break;case 13:case 32:hb=c,$a(c,a)}}}},tb={mouseover:function(){na&&(clearInterval(jb),na=!1,gc=!0)},mouseout:function(){gc&&(Kc(),gc=!1)}},ub={visibilitychange:function(){X.hidden?na&&(clearInterval(jb),na=!1,hc=!0):
hc&&(Kc(),hc=!1)}},Ab={keydown:function(a){a=Ba(a);switch(a.keyCode){case 37:Ca(a,-1);break;case 39:Ca(a,1)}}},yb={touchstart:nd,touchmove:od,touchend:dc,touchcancel:dc},zb={mousedown:nd,mousemove:od,mouseup:dc,mouseleave:dc},Wb=Fa("controls"),uc=Fa("nav"),vc=B?!0:e.navAsThumbnails,tc=Fa("autoplay"),yd=Fa("touch"),zd=Fa("mouseDrag"),rb="tns-slide-active",Sb="tns-complete",nc={load:fd,error:fd},sc;if(Wb)var I=e.controlsContainer,Ad=e.controlsContainer?e.controlsContainer.outerHTML:"",J=e.prevButton,
K=e.nextButton,Nd=e.prevButton?e.prevButton.outerHTML:"",Od=e.nextButton?e.nextButton.outerHTML:"",vb,wb;if(uc)var ca=e.navContainer,Bd=e.navContainer?e.navContainer.outerHTML:"",O,Q=[],ec=Q,hb=-1,Aa=cb(),Eb=Aa,Vb="tns-nav-active";if(tc)var ld="forward"===e.autoplayDirection?1:-1,L=e.autoplayButton,Cd=e.autoplayButton?e.autoplayButton.outerHTML:"",sb=["<span class='tns-visually-hidden'>"," animation</span>"],jb,na,gc,gb,hc;if(yd||zd)var Ea={},fa={},cc,ab=!1,Da=0,Lc=C?function(a,b){return a.x-b.x}:
function(a,b){return a.y-b.y};B||g(ja||oa);Gb&&(Ya=Gb,Qa="translate",Md?(Qa+=C?"3d(":"3d(0px, ",Za=C?", 0px, 0px)":", 0px)"):(Qa+=C?"X(":"Y(",Za=")"));(function(){E&&Bc();Fa("gutter");W.className="tns-outer";aa.className="tns-inner";W.id=V+"-ow";aa.id=V+"-iw";sa&&(aa.className+=" tns-ah");""===q.id&&(q.id=V);Xa+=Uc||B?" tns-subpixel":" tns-no-subpixel";Xa+=Va?" tns-calc":" tns-no-calc";Xa+=" tns-"+e.axis;q.className+=Xa;if(r){var a=X.createElement("div");a.className="tns-ovh";W.appendChild(a);a.appendChild(aa)}else W.appendChild(aa);
Yb.insertBefore(W,q);aa.appendChild(q);for(a=0;a<u;a++){var b=z[a];b.id||(b.id=V+"-item"+a);T(b,"tns-item");!r&&wa&&T(b,wa);Y(b,{"aria-hidden":"true",tabindex:"-1"})}if(U){a=X.createDocumentFragment();b=X.createDocumentFragment();for(var c=U;c--;){var d=c%u,f=z[d].cloneNode(!0);za(f,"id");b.insertBefore(f,b.firstChild);r&&(d=z[u-1-d].cloneNode(!0),za(d,"id"),a.appendChild(d))}q.insertBefore(a,q.firstChild);q.appendChild(b);z=q.children}lc();Qc()})();var Dc=function(){return Z?r?function(){var a=ya,
b=pa;a+=fb;b-=fb;ba?(a+=1,--b):y&&ta%(y+H)&&--b;U&&(p>b?p-=u:p<a&&(p+=u))}:function(){if(p>pa)for(;p>=ya+u;)p-=u;else if(p<ya)for(;p<=pa-u;)p+=u}:function(){p=Math.max(ya,Math.min(pa,p))}}(),Kd=function(){return r?function(){F&&(q.style[F]="");F||!xa?(Ec(),xa&&"none"!==window.getComputedStyle(q).display||ra()):Gd(q,Ya,Qa,Za,Fc(),xa,ra);C||rc()}:function(){ib=[];var a={};a[Wa]=a[sd]=ra;S(z[Pa],a);N(z[p],a);kd(Pa,Ma,$b,!0);kd(p,wa,Ma);Wa&&sd&&xa&&"none"!==window.getComputedStyle(q).display||ra()}}();
return{version:"2.8.7",getInfo:ea,events:R,goTo:$a,play:function(){ia&&!na&&(Ub(),gb=!1)},pause:function(){na&&(Zb(),gb=!0)},isOn:Ac,updateSliderHeight:hd,refresh:Qc,destroy:function(){G.disabled=!0;G.ownerNode&&G.ownerNode.remove();S(qa,{resize:Yc});Ja&&S(X,Ab);I&&S(I,xb);ca&&S(ca,xc);S(q,tb);S(q,ub);L&&S(L,{click:Vc});ia&&clearInterval(jb);if(r&&Wa){var a={};a[Wa]=ra;S(q,a)}Ha&&S(q,yb);Ia&&S(q,zb);var b=[xd,Ad,Nd,Od,Bd,Cd];fc.forEach(function(a,c){var d="container"===a?W:e[a];if("object"===("undefined"===
typeof d?"undefined":_typeof(d))){var f=d.previousElementSibling?d.previousElementSibling:!1,g=d.parentNode;d.outerHTML=b[c];e[a]=f?f.nextElementSibling:g.firstElementChild}});fc=Ma=$b=Gc=wa=C=W=aa=q=Yb=xd=z=u=Bb=Nb=B=y=ba=H=ta=A=fb=mc=Ja=xa=Fb=Z=sa=G=ed=P=ib=U=D=jd=db=Jc=Ya=Qa=Za=pb=p=Pa=ya=pa=Hb=bb=Ra=zc=R=Xa=V=ja=Cb=Tb=oa=Db=xb=xc=tb=ub=Ab=yb=zb=Wb=uc=vc=tc=yd=zd=rb=Sb=nc=sc=ua=Oa=I=Ad=J=K=vb=wb=va=ca=Bd=O=Q=ec=hb=Aa=Eb=Vb=ia=Cc=ld=Na=Ka=L=Cd=La=sb=jb=na=gc=gb=hc=Ea=fa=cc=ab=Da=Lc=Ha=Ia=null;for(var c in this)"rebuild"!==
c&&(this[c]=null);Ac=!1},rebuild:function(){return Ed(c(e,ud))}}}}}();"use strict";
var rhSlider={setWidth:function(){for(var c=0;c<this.sliders.length;c++){var d=this.sliders[c],a=d.dataset;a.view=a.view||4;var b=d.getElementsByClassName("contentNiced")[0],e=b.getElementsByClassName("blockNiced")[0],f=b.getElementsByClassName("rh_tpl_block");if(1>f.length)return!1;b=d.getElementsByClassName("contentNiced")[0];f=b.getElementsByClassName("rh_tpl_block");for(d=0;d<f.length;d++){var g=f[d],h=b.offsetWidth/a.view,k=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;
a.responsa=a.responsa.replace("{","").replace("}","");a.responsa.split(",").forEach(function(a){a=a.replace(/"/g,"");a=a.split(":");var c=parseInt(a[0]);a=parseInt(a[1]);k<=c&&(h=b.offsetWidth/a)});g.style.width=h-2*a.margin+"px";g.style.marginRight=a.margin+"px";g.style.marginLeft=a.margin+"px"}e.style.width=f.length*(f[0].offsetWidth+2*a.margin)+1E3+"px";e.style.position="relative";e.style.left="-"+h+"px";e.style.right=+h+"px"}},adjustItens:function(c){var d=c.getElementsByClassName("contentNiced")[0];
c=d.getElementsByClassName("blockNiced")[0];d=d.getElementsByClassName("rh_tpl_block");if(1>d.length)return!1;for(var a=[].slice.call(d),b=d[d.length-1],e=0,f=1;f<a.length;f++)a[f]=d[e],e++;a[0]=b;var g=c.getElementsByTagName("ul")[0];g.innerHTML="";a.forEach(function(a){g.appendChild(a)})},setControllers:function(){for(var c=0;c<this.sliders.length;c++){var d=this.sliders[c],a=d.dataset;d.getElementsByClassName("contentNiced");a='<div class="navigatorNiced"><i class="'+a.left+'"></i><i class="'+
a.right+'"></i></div>';d.innerHTML+=a;a=this.sliders[c].getElementsByClassName("navigatorNiced")[0];d=a.children[1];a.children[0].addEventListener("click",function(){rhSlider.moveLeft(this.parentElement.parentElement)});d.addEventListener("click",function(){rhSlider.moveRight(this.parentElement.parentElement)});(function(a){if("undefined"===typeof Hammer){var b=0;(function h(){setTimeout(function(){try{var c=new Hammer(rhSlider.sliders[a]);c.on("swiperight",function(b){rhSlider.moveLeft(a)});c.on("swipeleft",
function(b){rhSlider.moveRight(a)})}catch(l){5>b&&(h(),b++)}},1E3)})()}else{var c=new Hammer(rhSlider.sliders[a]);c.on("swiperight",function(b){rhSlider.moveLeft(a)});c.on("swipeleft",function(b){rhSlider.moveRight(a)})}})(c)}},setListeners:function(){window.addEventListener("resize",function(){rhSlider.setWidth();setTimeout(rhSlider.setWidth(),300)})},moveLeft:function(c){isNaN(c)||(c=rhSlider.sliders[c]);var d=c.dataset,a=c.getElementsByClassName("contentNiced")[0],b=a.getElementsByClassName("blockNiced")[0];
a=a.getElementsByClassName("rh_tpl_block");var e=b.getElementsByTagName("ul")[0],f=a[a.length-1].cloneNode(!0),g=a[0].offsetWidth;g=g+2*parseFloat(a[0].style.marginLeft)+"px";var h=c.getElementsByClassName("navigatorNiced")[0],k=h.children[0];k.style.pointerEvents="none";b.style.pointerEvents="none";h.style.pointerEvents="none";b.style.transition="ease-out left "+d.transition+"s";a[a.length-1].remove();b.style.left="0px";b.style.right="0px";setTimeout(function(){b.style.transition="none";e.insertBefore(f,
e.firstChild);b.style.left="-"+g;b.style.right=g;k.style.pointerEvents="initial";b.style.pointerEvents="initial";h.style.pointerEvents="initial";e.firstChild.classList.contains("rh-product-vtex")&&rhVtexShelf.bindActionsToProduct(e.firstChild)},parseFloat(1E3*d.transition))},moveRight:function(c){isNaN(c)||(c=rhSlider.sliders[c]);var d=c.dataset,a=c.getElementsByClassName("contentNiced")[0],b=a.getElementsByClassName("blockNiced")[0],e=a.getElementsByClassName("rh_tpl_block"),f=b.getElementsByTagName("ul")[0],
g=e[0].cloneNode(!0),h=e[0].offsetWidth;h=h+2*parseFloat(e[0].style.marginLeft)+"px";if(parseFloat(b.style.left)>h)return!1;var k=c.getElementsByClassName("navigatorNiced")[0],l=k.children[1];l.style.pointerEvents="none";b.style.pointerEvents="none";k.style.pointerEvents="none";b.style.transition="ease-out all "+d.transition+"s";b.style.left="-"+2*parseFloat(h)+"px";b.style.right=2*parseFloat(h)+"px";setTimeout(function(){b.style.transition="none";f.insertBefore(g,f.children[f.children.length-1].nextElementSibling);
e[0].remove();f.firstChild.classList.contains("rh-product-vtex")&&rhVtexShelf.bindActionsToProduct(f.children[f.children.length-1]);b.style.left="-"+h;b.style.right=h;l.style.pointerEvents="initial";b.style.pointerEvents="initial";k.style.pointerEvents="initial"},parseFloat(1E3*d.transition))},getHammer:function(){if(!document.getElementById("__rhHammerJS__"))if("undefined"!==typeof require&&"undefined"!==typeof require.config&&"undefined"!==typeof require.version)setTimeout(function(){var a=document.createElement("script"),
b=document.getElementsByTagName("script");a.id="__rhHammerJS__";a.src="https://roihero.com.br/widget/js/hammer.min.js";b[b.length-1].parentNode.insertBefore(a,b[b.length])},2E3);else{var c=document.createElement("script"),d=document.getElementsByTagName("script");c.id="__rhHammerJS__";c.src="https://roihero.com.br/widget/js/hammer.min.js";d[d.length-1].parentNode.insertBefore(c,d[d.length])}},createSliders:function(){this.getHammer();this.sliders=document.getElementsByClassName("touchNiced");this.setWidth();
this.setListeners();this.setControllers();for(var c=0;c<this.sliders.length;c++)this.adjustItens(this.sliders[c])}};rhSlider.createSliders();var Wapp=Wapp||{};Wapp.TplFnc={};
(function(c,d,a){a={open:c.getElementsByClassName("rh_tpl_kit_offerslimited_open")[0],close:c.getElementsByClassName("rh_tpl_kit_offerslimited_close")[0],closeOverlay:c.getElementsByClassName("rh_tpl_close")[0]};Wapp.TplFnc.Init=function(){Wapp.TplFnc.Listen()};Wapp.TplFnc.Listen=function(){a.open&&(a.open.addEventListener("click",Wapp.TplFnc.Sidebar,!0),a.close.addEventListener("click",Wapp.TplFnc.Sidebar,!0));a.closeOverlay&&a.closeOverlay.addEventListener("click",Wapp.TplFnc.Overlay,!0)};Wapp.TplFnc.Sidebar=
function(b){var c=b.target.classList.contains("fa")?b.target.parentElement:b.target,d=c.nextElementSibling;c.classList.contains("rh_tpl_kit_offerslimited_close")&&(d=c.parentElement);d.classList.contains("active")?(d.classList.remove("active"),a.open.classList.remove("active")):(d.classList.add("active"),a.open.classList.add("active"));b.preventDefault();return!1};Wapp.TplFnc.Overlay=function(a){var b=document.getElementsByClassName("gridOverlay")[0];b.classList.remove("active");b.style.opacity="0";
setTimeout(function(){b.style.display="none"},500);a.preventDefault();return!1};(function e(){document.getElementsByClassName("rh_tpl_kit_offerslimited")[0]?setTimeout(function(){Wapp.TplFnc.Init()},200):setTimeout(function(){e()},200)})()})(document,window,"Private");
if(document.getElementById("rh-ol-overlay")){var overlay=document.getElementById("rh-ol-overlay"),btnOpen=document.getElementById("rh-ol-open"),btnClose=document.getElementById("rh-ol-close"),btnExit=document.getElementById("rh-ol-exit"),block=overlay.parentElement;btnOpen.addEventListener("click",function(){this.parentElement.classList.remove("active");overlay.classList.add("active");block.classList.add("active")});btnClose.addEventListener("click",function(){btnOpen.parentElement.classList.add("active");
overlay.classList.remove("active");block.classList.remove("active")});btnExit.addEventListener("click",function(){btnOpen.parentElement.classList.remove("active");setTimeout(function(){block.style.display="none";block.style.visibility="hidden";block.style.pointerEvents="none";block.style.height="0";block.style.width="0";block.style.overflow="hidden";block.style.zIndex="-1"},2E3)})}
window["rh-overlay"]=function(){var c=document.getElementsByClassName("gridOverlay")[0];if(c){window.rh_lite_mostrou=0;var d=function(a){a=a?a:window.event;if(0>=a.clientY&&(a=a.relatedTarget||a.toElement,!a||"HTML"==a.nodeName))return 0==window.rh_lite_mostrou&&(c.style.display="block",rhSlider.setWidth(),setTimeout(function(){c.style.opacity="1"},500),window.rh_lite_mostrou=1,a=new Date,a.setHours(a.getHours()+3),document.cookie="rhOverlay=1; expires="+a.toUTCString()+"; path=/"),!1};(function(a,
b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)})(document,"mouseout",function(a){d(a)})}window.addEventListener("click",window["rh-overlay"].checkClickOverlay)};var rhCheckOV=function rhCheckOV(){document.getElementsByClassName("gridOverlay")[0]?(window["rh-overlay"](),Wapp.TplFnc.Listen()):setTimeout(function(){rhCheckOV()},200)};rhCheckOV();var container=document.getElementsByClassName("rh_tpl_fixed_footer")[0];
if(container){var rhMostraFixedFooter=function(c){c=document.documentElement;var d=document.body,a=document.documentElement;d=Math.max(d.scrollHeight,d.offsetHeight,a.clientHeight,a.scrollHeight,a.offsetHeight);d/100*50+((window.pageYOffset||c.scrollTop)-(c.clientTop||0))>=d?(container.style.display="block",rhSlider.setWidth(),setTimeout(function(){container.style.opacity="1"},200)):(container.style.display="none",container.style.opacity="0")};document.addEventListener("scroll",function(c){rhMostraFixedFooter(c)});
btnClose=container.getElementsByClassName("btn_close")[0];btnClose.addEventListener("click",function(){container.style.height=container.offsetHeight+"px";setTimeout(function(){container.style.height=0},50)})}
roiHeroComponents.vtexShelf={shelfs:[],listen:function(){for(var c=document.querySelectorAll(".rh-vtex-shelf"),d="/api/catalog_system/pub/products/search?",a=0;a<c.length;a++){for(var b=c[a].querySelectorAll(".rh_tpl_block"),e=0;e<b.length;e++){var f=b[e].dataset.rhSku;f=f.split(",")[0];d+="&fq=skuId:"+f}this.shelfs.push({container:c[a],products:b,getUrl:d});this.getProducts(d,a)}},getProducts:function(c,d){var a=new XMLHttpRequest;a.open("get",c,!0);a.onreadystatechange=function(){if(200==a.status&&
4==a.readyState){var b=JSON.parse(a.responseText);roiHeroComponents.vtexShelf.setPrices(b,d)}};a.send(null)},setPrices:function(c,d){console.log(c);var a=roiHeroComponents.vtexShelf.shelfs[d];d=a.products;for(var b=[],e=0;e<d.length;e++){var f=d[e].dataset.rhSku;f=f.split(",")[0];for(var g=0;g<c.length;g++)for(var h=c[g].items,k=0;k<h.length;k++){var l=h[k];if(l.itemId==f){k=l.sellers[0].commertialOffer.ListPrice;var m=l.sellers[0].commertialOffer.Price;if(0==m&&0==k)for(var v=0;v<h.length;v++){if(l=
h[v],k=l.sellers[0].commertialOffer.ListPrice,m=l.sellers[0].commertialOffer.Price,0!=k&&0!=m){b.push(l);break}}else b.push(l);break}}}console.log(a.container);c=a.container.dataset.rhCurrency;for(e=0;e<b.length;e++)h=b[e].sellers[0],a=h.commertialOffer.ListPrice,f=h.commertialOffer.Price,g=h.commertialOffer.Installments[0].NumberOfInstallments,h=h.commertialOffer.Installments[0].TotalValuePlusInterestRate,f=parseFloat(f).toFixed(2),a=parseFloat(a).toFixed(2),console.log(f),console.log(a),console.log(g),
console.log(h),console.log("----------------"),g=d[e].querySelector('[data-rh-bind="price"]'),"R$"===c&&(f=(f+"").replace(".",","),(a+"").replace(".",",")),g.innerHTML=c+" "+f},init:function(){this.salesChannel=roiHeroComponents.util.getCookie("VTEXSC")||roiHeroComponents.util.getCookie("salesChannel")||"1";this.listen()}};roiHeroComponents.vtexShelf.init();
roiHeroComponents.rhCompreJunto={apps:[],checkIfArrayIsAllEquall:function(c){return!!c.reduce(function(c,a){return c===a?c:NaN})},listen:function(){for(var c=document.getElementsByClassName("dynamic-buy-together"),d=0;d<c.length;d++)this.apps.push({buyTogether:[],mainContainer:c[d],products:[]});for(d=0;d<this.apps.length;d++){c=this.apps[d].mainContainer;for(var a=c.getElementsByClassName("rh_tpl_block"),b=0;b<a.length;b++){var e=a[b],f=e.dataset.rhCjProdName,g=[];e.dataset.rhCjProduct=b;e.dataset.rhCjApp=
d;var h=e.querySelector(".rh-price").value;h=h.toUpperCase().replace(",",".").replace("R$","").replace("$","").trim();h=parseFloat(h);var k=e.querySelector(".rh-price-normal").value;k=k.toUpperCase().replace(",",".").replace("R$","").replace("$","").trim();k=isNaN(parseFloat(k))?0:k;k=0!==k?parseFloat(k||0):0;var l=e.querySelector(".rh-colors");l=null!==l?l.value.split(","):"";var m=e.querySelector(".rh-sizes");m=null!==m?m.value.split(","):"";for(var v=e.querySelector(".rh-sku").value.split(","),
n=0;n<v.length;n++){var ha={};""!=l&&(ha.color=l[n]);""!=m&&(ha.size=m[n]);ha.sku=v[n];g.push(ha)}this.apps[d].products.push({name:f,container:e,types:g,price:h,normalPrice:k});f=e.querySelector(".rh-variant-select");if(!this.checkIfArrayIsAllEquall(l)){g=document.createElement("select");l=roiHeroComponents.util.removeDuplicatesFromArray(l);g.dataset.rhCjApp=d;g.dataset.rhCjProduct=b;g.classList.add("rh-color-select");for(n=0;n<l.length;n++)g.innerHTML+='<option value="'+l[n]+'">'+l[n]+"</option>";
n=document.createElement("div");n.classList.add("rh-variant-select-form","rh-variant-color");n.innerHTML="<label>Color</label>";n.appendChild(g);f.appendChild(n);n=e.querySelector(".rh-color-select");n.addEventListener("change",roiHeroComponents.rhCompreJunto.changeColor)}if(!this.checkIfArrayIsAllEquall(m)){l=document.createElement("select");m=roiHeroComponents.util.removeDuplicatesFromArray(m);l.dataset.rhCjApp=d;l.dataset.rhCjProduct=b;l.classList.add("rh-size-select");for(n=0;n<m.length;n++)l.innerHTML+=
'<option value="'+m[n]+'">'+m[n]+"</option>";n=document.createElement("div");n.classList.add("rh-variant-select-form","rh-variant-size");n.innerHTML="<label>Size</label>";n.appendChild(l);f.appendChild(n);n=e.querySelector(".rh-size-select");n.addEventListener("change",roiHeroComponents.rhCompreJunto.changeSize)}0!==b&&(m=document.createElement("div"),m.classList.add("rh-change-product-container"),m.innerHTML='<span class="rh-change-product" data-rh-cj-app="'+d+'" data-rh-cj-product="'+b+'"></span>',
e.appendChild(m),e.querySelector('.rh-change-product[data-rh-cj-product="'+b+'"]').addEventListener("click",function(){roiHeroComponents.rhCompreJunto.changeProduct(this)}))}console.log(this.apps);roiHeroComponents.rhCompreJunto.apps[d].buyTogether=[this.apps[d].products[0].types[0].sku,this.apps[d].products[1].types[0].sku];e=roiHeroComponents.rhCompreJunto.apps[d].mainContainer;a=roiHeroComponents.rhCompreJunto.apps[d].products[0].name;b=roiHeroComponents.rhCompreJunto.apps[d].products[1].name;
m=e.querySelector(".rh-cj-prodname-1");e=e.querySelector(".rh-cj-prodname-2");m.innerHTML=a;e.innerHTML=b;c.querySelector(".rh-add-to-cart").dataset.rhBuyTogether=d;e=c.querySelector(".rh-cj-sum-price");a=roiHeroComponents.rhCompreJunto.apps[d].products[0].price;b=roiHeroComponents.rhCompreJunto.apps[d].products[1].price;m=(a+b).toFixed(2);c.dataset.rhCurrency&&(l=c.dataset.rhCurrency,"R$"===l&&(a=(a+"").replace(".",","),b=(b+"").replace(".",","),m=(m+"").replace(".",",")));e.innerHTML=m;e=c.querySelector(".rh-cj-sum-old-price");
a=roiHeroComponents.rhCompreJunto.apps[d].products[0].normalPrice;b=roiHeroComponents.rhCompreJunto.apps[d].products[1].normalPrice;m=(a+b).toFixed(2);0<a+b?(a=0>=a?roiHeroComponents.rhCompreJunto.apps[d].products[0].price:a,b=0>=a?roiHeroComponents.rhCompreJunto.apps[d].products[1].price:b,c.dataset.rhCurrency&&(l=c.dataset.rhCurrency,"R$"===l&&(a=(a+"").replace(".",","),b=(b+"").replace(".",","),m=(m+"").replace(".",","))),e.innerHTML=m,e.style.display="block"):e.style.display="none"}},changeSize:function(){var c=
roiHeroComponents.rhCompreJunto.apps[parseInt(this.dataset.rhCjApp)],d=c.products[parseInt(this.dataset.rhCjProduct)],a={},b=c.mainContainer.querySelector(".rh-color-select");b=null===b?"":b.value;var e=this.value;""!==b&&(a.color=b);a.size=e;b=d.types.slice(0);for(e=0;e<b.length;e++){var f={};Object.assign(f,b[e]);delete f.sku;for(var g=Object.keys(f),h=0;h<g.length;h++)a.hasOwnProperty(g[h])||delete f[g[h]];Object.values(f).join(",")==Object.values(a).join(",")&&(0==this.dataset.rhCjProduct?c.buyTogether[0]=
d.types[e].sku:c.buyTogether[1]=d.types[e].sku,console.log(d.types[e]),console.log(c))}},changeColor:function(){var c=roiHeroComponents.rhCompreJunto.apps[parseInt(this.dataset.rhCjApp)],d=c.products[parseInt(this.dataset.rhCjProduct)];c.mainContainer.querySelector(".rh-color-select");console.log(d);var a=d.container.querySelector(".rh-size-select");var b=d.container.querySelector(".rh-color-select");if(a&&b){for(var e=a.getElementsByTagName("option"),f=0;f<e.length;f++){c={color:b.value,size:e[f].value};
for(var g="",h=0;h<d.types.length;h++){var k={};Object.assign(k,d.types[h]);delete k.sku;if(Object.keys(c).join(",")===Object.keys(c).join(",")){var l=Object.values(k).join(","),m=Object.values(c).join(",");l===m&&(g=d.types[h].sku)}if(""!==g){console.log("SKU: "+g+" COR:"+b.value+" TAMANHO:"+e[f].value);e[f].removeAttribute("disabled");roiHeroComponents.dynamicShelf.toggleOption("enable",a,k.size);break}}""===g&&(console.log("Produto n\u00e3o dispon\u00edvel na cor "+b.value+" e tamanho "+e[f].value),
e[f].setAttribute("disabled",!0))}roiHeroComponents.rhCompreJunto.changeToNextActiveOption(a);roiHeroComponents.rhCompreJunto.checkVariants(d.container)}},checkVariants:function(c){var d=c.querySelector(".rh-size-select"),a=c.querySelector(".rh-color-select");c=d||a;var b=c.dataset.rhCjProduct,e=roiHeroComponents.rhCompreJunto.apps[c.dataset.rhCjApp],f=e.products[b];c=f.container;var g="",h={};a&&(h.color=a.value);d&&(h.size=d.value);for(d=0;d<f.types.length;d++){a={};Object.assign(a,f.types[d]);
delete a.sku;if(Object.keys(h).join(",")===Object.keys(h).join(",")){a=Object.values(a).join(",");var k=Object.values(h).join(",");a===k&&(g=f.types[d].sku)}if(""!==g){c.dataset.rhDsSku=g;0===b?e.buyTogether[0]=g:e.buyTogether[1]=g;console.log(e);break}}},changeProduct:function(c){var d=parseInt(c.dataset.rhCjApp),a=parseInt(c.dataset.rhCjProduct);d=this.apps[d];c=d.mainContainer;c.querySelector('li+[data-rh-cj-product="'+a+'"]').setAttribute("style","display: none !important");a=c.querySelector('li+[data-rh-cj-product="'+
(a+1)+'"]')?c.querySelector('li+[data-rh-cj-product="'+(a+1)+'"]'):c.querySelector('li+[data-rh-cj-product="1"]');a.setAttribute("style","display: block !important");var b=a.dataset.rhCjProdName;c.querySelector(".rh-cj-prodname-2").innerHTML=b;b=(d.products[0].price+d.products[a.dataset.rhCjProduct].price).toFixed(2);if(c.dataset.rhCurrency){var e=c.dataset.rhCurrency;"R$"===e&&(b=(b+"").replace(".",","))}c.querySelector(".rh-cj-sum-price").innerHTML=b;b=c.querySelector(".rh-cj-sum-old-price");e=
d.products[0].normalPrice;var f=d.products[a.dataset.rhCjProduct].normalPrice;0<e+f?(e=0>=e?d.products[0].price:e,f=0>=f?d.products[a.dataset.rhCjProduct].price:f,f=(e+f).toFixed(2),c.dataset.rhCurrency&&(e=c.dataset.rhCurrency,"R$"===e&&(f=(f+"").replace(".",","))),b.innerHTML=f,b.style.display="block"):b.style.display="none";c=a.querySelector(".rh-sku").value.split(",")[0];d.buyTogether[1]=c},changeToNextActiveOption:function(c){for(var d=c.getElementsByTagName("option"),a=0;a<d.length;a++)if(null===
d[a].getAttribute("disabled")&&d[a].value===c.value)return!1;for(a=0;a<d.length;a++)if(null===d[a].getAttribute("disabled")){c.value=d[a].value;break}}};roiHeroComponents.rhCompreJunto.listen();
roiHeroComponents.dynamicShelf={apps:[],addOptions:function(){for(var c=document.getElementsByClassName("rh-dynamic-shelf"),d=0;d<c.length;d++){this.apps.push({mainContainer:c[d],products:[]});var a=this.apps[d].mainContainer.getElementsByClassName("rh_tpl_block");console.log(this.apps);for(var b=0;b<a.length;b++){var e=a[b],f=e.querySelector(".rh-variant-select"),g=[],h=e.querySelector(".rh-colors");h=null!==h&&""!==h?h.value.split(","):"";var k=e.querySelector(".rh-sizes");k=null!==k&&""!==k?k.value.split(","):
"";var l=e.querySelector(".rh-sku").value.split(",");e.dataset.rhDsSku=l[0];if(!k.reduce(function(a,b){return a===b?a:NaN})&&1<k.length){var m=document.createElement("select"),v=roiHeroComponents.util.removeDuplicatesFromArray(k);m.dataset.rhDsApp=d;m.dataset.rhDsProduct=b;m.classList.add("rh-size-select");for(var n=0;n<v.length;n++)m.innerHTML+='<option value="'+v[n]+'">'+v[n]+"</option>";n=document.createElement("div");n.classList.add("rh-variant-select-form","rh-variant-size");n.innerHTML="<label>Size</label>";
n.appendChild(m);f.appendChild(n)}if(!h.reduce(function(a,b){return a===b?a:NaN})&&1<h.length){m=document.createElement("select");v=roiHeroComponents.util.removeDuplicatesFromArray(h);m.dataset.rhDsApp=d;m.dataset.rhDsProduct=b;m.classList.add("rh-color-select");for(n=0;n<v.length;n++)m.innerHTML+='<option value="'+v[n]+'">'+v[n]+"</option>";n=document.createElement("div");n.classList.add("rh-variant-select-form","rh-variant-color");n.innerHTML="<label>Color</label>";n.appendChild(m);f.appendChild(n)}for(n=
0;n<l.length;n++)f={},""!=h&&(f.color=h[n]),""!=k&&(f.size=k[n]),f.sku=l[n],g.push(f);this.apps[d].products.push({types:g,container:e})}console.log(this.apps[d])}},listen:function(){this.addOptions();for(var c=0;c<this.apps.length;c++)for(var d=this.apps[c],a=0;a<d.products.length;a++){var b=d.products[a].container,e=b.querySelector(".rh-color-select");b=b.querySelector(".rh-size-select");e&&e.addEventListener("change",this.changeColor);b&&b.addEventListener("change",this.changeSize)}},changeColor:function(){roiHeroComponents.dynamicShelf.checkOptions(roiHeroComponents.dynamicShelf.apps[this.dataset.rhDsApp].products[this.dataset.rhDsProduct].container);
console.log("-------------------------------------")},changeSize:function(){roiHeroComponents.dynamicShelf.checkVariants(roiHeroComponents.dynamicShelf.apps[this.dataset.rhDsApp].products[this.dataset.rhDsProduct].container)},checkVariants:function(c){var d=c.querySelector(".rh-size-select"),a=c.querySelector(".rh-color-select");c=d||a;var b=roiHeroComponents.dynamicShelf.apps[c.dataset.rhDsApp].products[c.dataset.rhDsProduct];c=b.container;var e="",f={};a&&(f.color=a.value);d&&(f.size=d.value);for(d=
0;d<b.types.length;d++){a={};Object.assign(a,b.types[d]);delete a.sku;if(Object.keys(f).join(",")===Object.keys(f).join(",")){f.hasOwnProperty("color")||delete a.color;f.hasOwnProperty("size")||delete a.size;a=Object.values(a).join(",");var g=Object.values(f).join(",");a===g&&(console.log(a),console.log(g),console.log(b.types[d]),e=b.types[d].sku)}if(""!==e){c.dataset.rhDsSku=e;break}else console.log("que?")}},checkOptions:function(c){var d=c.querySelector(".rh-size-select"),a=c.querySelector(".rh-color-select"),
b=roiHeroComponents.dynamicShelf.apps[a.dataset.rhDsApp].products[a.dataset.rhDsProduct];c=b.container;if(d&&a){for(var e=d.getElementsByTagName("option"),f=0;f<e.length;f++){for(var g={color:a.value,size:e[f].value},h="",k=0;k<b.types.length;k++){var l={};Object.assign(l,b.types[k]);delete l.sku;if(Object.keys(g).join(",")===Object.keys(g).join(",")){var m=Object.values(l).join(","),v=Object.values(g).join(",");m===v&&(h=b.types[k].sku)}if(""!==h){console.log("SKU: "+h+" COR:"+a.value+" TAMANHO:"+
e[f].value);e[f].removeAttribute("disabled");roiHeroComponents.dynamicShelf.toggleOption("enable",d,l.size);break}}""===h&&(console.log("Produto n\u00e3o dispon\u00edvel na cor "+a.value+" e tamanho "+e[f].value),e[f].setAttribute("disabled",!0))}roiHeroComponents.dynamicShelf.changeToNextActiveOption(d);roiHeroComponents.dynamicShelf.checkVariants(c)}},toggleOption:function(c,d,a){d=d.getElementsByTagName("option");for(var b=0;b<d.length;b++)d[b].value===a&&("enable"===c?d[b].removeAttribute("disabled"):
d[b].setAttribute("disabled","true"))},changeToNextActiveOption:function(c){for(var d=c.getElementsByTagName("option"),a=0;a<d.length;a++)if(null===d[a].getAttribute("disabled")&&d[a].value===c.value)return!1;for(a=0;a<d.length;a++)if(null===d[a].getAttribute("disabled")){c.value=d[a].value;break}}};roiHeroComponents.dynamicShelf.listen();
if("44c9b30f7a5334e5c1c81ad08781cd89d33d02c0"===rhClientId){for(var shelfs=document.querySelectorAll(".rh-block"),i=0;i<shelfs.length;i++)for(var prods=shelfs[i].querySelectorAll("li"),_i=0;_i<prods.length;_i++){var prod=prods[_i],prodImg=prod.querySelector("img");prodImg.src+="-1912-998"}var changeImgSearchbar=function d(){"undefined"!==typeof rh_lite_obj?rh_lite_obj.forEach(function(a){a.link_image+="-1912-998"}):setTimeout(function(){d()},500)};changeImgSearchbar()}"use strict";
roiHeroComponents.ofertaLimitada={init:function(){document.getElementsByClassName("rh-limited-offer")[0]&&this.addListeners()},addListeners:function(){this.mainContainer=document.getElementsByClassName("rh-limited-offer")[0];this.olOpen=this.mainContainer.getElementsByClassName("rh-lo-open")[0];this.olOverlay=this.mainContainer.getElementsByClassName("rh-lo-overlay")[0];this.olCloseOverlay=this.mainContainer.getElementsByClassName("rh-lo-close")[0];this.olExit=this.mainContainer.getElementsByClassName("rh-lo-exit")[0];
this.olOpen.addEventListener("click",this.toggleOverlay);this.olCloseOverlay.addEventListener("click",this.closeOverlay);this.olExit.addEventListener("click",this.exit);window.addEventListener("click",this.checkIfClickedOutside)},closeOverlay:function(){roiHeroComponents.ofertaLimitada.olOpen.classList.add("rh-active");roiHeroComponents.ofertaLimitada.olOverlay.classList.remove("rh-active");roiHeroComponents.ofertaLimitada.mainContainer.classList.remove("rh-active")},openOverlay:function(){roiHeroComponents.ofertaLimitada.olOpen.classList.remove("rh-active");
roiHeroComponents.ofertaLimitada.olOverlay.classList.add("rh-active");roiHeroComponents.ofertaLimitada.mainContainer.classList.add("rh-active")},toggleOverlay:function(){roiHeroComponents.ofertaLimitada.olOverlay.classList.contains("rh-active")?roiHeroComponents.ofertaLimitada.closeOverlay():roiHeroComponents.ofertaLimitada.openOverlay()},exit:function(){roiHeroComponents.ofertaLimitada.mainContainer.style.display="none";roiHeroComponents.ofertaLimitada.mainContainer.style.zIndex="-1";roiHeroComponents.ofertaLimitada.mainContainer.style.visibility=
"hidden"},checkIfClickedOutside:function(c){c.target.classList.contains("rh-limited-offer")&&roiHeroComponents.ofertaLimitada.closeOverlay()}};roiHeroComponents.ofertaLimitada.init();
roiHeroComponents.overlay={alreadyShown:!1,init:function(){document.querySelector('[data-rh-role="roi-hero-overlay"]')&&this.addListeners()},addListeners:function(){this.container=document.querySelector('[data-rh-role="roi-hero-overlay"]');this.container.querySelector(".rh-eo-close").addEventListener("click",roiHeroComponents.overlay.hide);document.addEventListener("mouseout",roiHeroComponents.overlay.checkIfIsOutsideWindow);window.addEventListener("click",roiHeroComponents.overlay.checkIfClickedOutsideOverlay)},
checkIfIsOutsideWindow:function(c){0>=c.clientY&&setTimeout(function(){var d=c.relatedTarget||c.toElement;if(!d||"HTML"==d.nodeName)return roiHeroComponents.overlay.show(),!1},500)},checkIfClickedOutsideOverlay:function(c){c=c.target;"undefined"!==typeof c.dataset.rhRole&&"roi-hero-overlay"===c.dataset.rhRole&&roiHeroComponents.overlay.hide()},show:function(){var c=roiHeroComponents.overlay.container;roiHeroComponents.overlay.alreadyShown||(c.classList.add("rh-active"),c.style.display="block",c.style.visibility=
"visible",roiHeroComponents.overlay.setCookie(),roiHeroComponents.overlay.alreadyShown=!0,document.removeEventListener("mouseout",roiHeroComponents.overlay.checkIfIsOutsideWindow))},hide:function(){var c=roiHeroComponents.overlay.container;c.classList.remove("rh-active");setTimeout(function(){c.style.display="none";c.style.visibility="hidden";c.style.zIndex="-1"},1E3);window.removeEventListener("click",roiHeroComponents.overlay.checkIfClickedOutsideOverlay)},setCookie:function(){var c=new Date;c.setHours(c.getHours()+
3);document.cookie="rhOverlay=1; expires="+c.toUTCString()+"; path=/"}};roiHeroComponents.overlay.init();
roiHeroComponents.slider={sliders:[],init:function(){for(var c=document.querySelectorAll('[data-rh-role="roi-hero-slider"]'),d=0;d<c.length;d++){var a=c[d],b=a.querySelector('[data-rh-role="slider-slide"]'),e="rhSlider"+d;b.id=e;b=JSON.parse(a.dataset.responsive);var f=parseInt(a.dataset.speed),g=parseInt(a.dataset.view);a=parseInt(a.dataset.edgePadding);e=tns({container:"#"+e,items:g,slideBy:"page",mouseDrag:!0,swipeAngle:!1,speed:f,responsive:b,edgePadding:a});this.sliders.push(e)}}};roiHeroComponents.slider.init();
"use strict";window.rhVtexShelf={};rhVtexShelf.shelfs=[];rhVtexShelf.products={};rhVtexShelf.util={};rhVtexShelf.config="85f1002bf139bebdb7f0d07b31fa14155aea9dfc"===rhClientId?{addToCartAditionalScript:function(){popCart();$("#popCart").fadeIn(400)}}:{};
(function(c,d){rhVtexShelf.init=function(){this.getSalesChannel();this.createShelfs();"85f1002bf139bebdb7f0d07b31fa14155aea9dfc"===rhClientId?this.getAllProductsForStaples():this.getAllProducts()};rhVtexShelf.util.toReais=function(a){var b=c.currencyCli?c.currencyCli:"R$",d=/\.?(\d{1,2})$/g,f=/(\d)(?=(\d{3})+(?!\d))/g;a?("string"===typeof a&&(a=parseFloat(a)),a=a.toFixed(2),"R$"===b?(a=a.replace(d,",$1"),a=a.replace(f,"$1.")):(a=a.replace(d,".$1"),a=a.replace(f,"$1,"))):a="R$"===b?"0,00":"0.00";return b+
" "+a};rhVtexShelf.util.replaceAll=function(a,b,c){return a.replace(new RegExp(b,"g"),c)};rhVtexShelf.getSalesChannel=function(){try{rhVtexShelf.salesChannel=salesChannel||null,null===salesChannel&&(vtexjs.checkout.orderForm||vtexjs.checkout.getOrderForm().then(function(){rhVtexShelf.salesChannel=vtexjs.checkout.orderForm.salesChannel}))}catch(a){}rhVtexShelf.salesChannel=rhVtexShelf.salesChannel||"1"};rhVtexShelf.setPrices=function(a){a=a.querySelectorAll(".rh-product");for(var b=0;b<a.length;b++)rhVtexShelf.setProduct(a[b])};
rhVtexShelf.setProduct=function(a){var b=a.innerHTML,c=a.dataset.rhSku,d=this.products[c],g=!1,h=a.dataset.rhId,k=rhVtexShelf.shelfs[a.dataset.rhShelf],l=k.vtexData;if(d)for(l=k.vtexData,k=0;k<l.length;k++){var m=l[k];h==m.productId&&1<m.items.length&&(g=!0)}else for(console.log("Produto "+c+" n\u00e3o encontrado!"),a.classList.add("rh-product-unavailable"),m=0;m<l.length;m++)if(k=l[m],h==k.productId){h=k.items;1<k.items.length&&(g=!0);for(l=0;l<h.length;l++)if(k=h[l],rhVtexShelf.products[k.itemId]){a.dataset.rhSku=
k.itemId;d=k;break}break}"undefined"===typeof d?console.log("O produto com o ID "+a.dataset.rhId+" n\u00e3o foi encontrado."):(a.dataset.rhAvailableQuantity=d.sellers[0].commertialOffer.AvailableQuantity,0>=d.sellers[0].commertialOffer.Price&&0>=d.sellers[0].commertialOffer.Price?(a.classList.add("rh-product-unavailable"),console.log("Produto vindo da API com pre\u00e7o zerado, carregado como esgotado:"),console.log(rhVtexShelf.products[c])):(b=rhVtexShelf.loadInfoToHtml(b,d),c=document.createElement("ul"),
c.innerHTML=b,b=c.querySelector(".rh-product-info"),a.querySelector(".rh-product-info").innerHTML=b.innerHTML,b=c.querySelector(".rh-product-image"),a.querySelector(".rh-product-image").outerHTML=b.outerHTML,g&&(a.dataset.rhSku=""),a.querySelector(".rh-product-info.rh-loading").classList.remove("rh-loading")))};rhVtexShelf.loadInfoToHtml=function(a,b){var c=this.util.toReais(b.sellers[0].commertialOffer.ListPrice),d=this.util.toReais(b.sellers[0].commertialOffer.Price);a=a.split("{check_oldprice}");
var g=a[1];c===d?(g=g.split("{case_false}")[1],g=this.util.replaceAll(g,"{sale_price}",'<span class="rh-product-new-price">'+d+"</span>")):(g=g.split("{case_true}")[1],c='<span class="rh-product-old-price">'+c+"</span>",g=this.util.replaceAll(g,"{sale_price}",'<span class="rh-product-new-price">'+d+"</span>"),g=this.util.replaceAll(g,"{old_price}",c));a=a[0]+g+a[2];d=b.sellers[0].commertialOffer.Installments;c=b=g=0;if(0<d.length){for(b=0;b<d.length;b++)1<d[b].NumberOfInstallments&&(g=b);b=d[g].NumberOfInstallments;
c=rhVtexShelf.util.toReais(d[g].Value)}a=a.split("{check_installment}");1>=b?a=a[0]+a[2]:(d=a[1],b='<span class="rh-installment-times">'+b+"</span>",d=rhVtexShelf.util.replaceAll(d,"{installment_value}",'<span class="rh-installment-value">'+c+"</span>"),d=rhVtexShelf.util.replaceAll(d,"{installment_times}",b),a=a[0]+d+a[2]);return a};rhVtexShelf.createShelfs=function(){for(var a=d.querySelectorAll(".rh-vtex-smart-shelf"),b={},c=0;c<a.length;c++){var f=a[c],g=f.querySelectorAll(".rh-product"),h=f.querySelector(".rh-vtex-smart-shelf-config"),
k="";h&&(k=JSON.parse(h.value));h=[];for(var l=[],m=0;m<g.length;m++){var v=g[m];if(0>v.innerHTML.indexOf("{sale_price}")&&0>v.innerHTML.indexOf("{old_price}"))v.dataset.rhShelf=c;else{b[v.dataset.rhId]=v.outerHTML;if(v.querySelector(".rh-sku")){var n=v.querySelector(".rh-sku").value.trim();n=n.split(",")[0];h.push(n);v.dataset.rhSku=n}else v.dataset.rhSku=v.dataset.rhSku.split(",")[0];v.dataset.rhShelf=c;v=v.dataset.rhId.trim();l.push(v)}}f.dataset.rhShelf=c;this.shelfs[c]={container:f,skuList:h,
idList:l,productModel:b,cfg:k};g=f.querySelector(".rh-buy-together-new-price");f=f.querySelector(".rh-buy-together-old-price");g&&f&&g.innerHTML===f.innerHTML&&(f.parentElement.style.display="none")}};rhVtexShelf.getProductsById=function(a,b){var c=a.length-1,d=new XMLHttpRequest;a="fq=productId:"+a.join("&fq=productId:");var g="";g=10<c?"/api/catalog_system/pub/products/search?"+a+"&_from=0&_to="+c+"&sc="+rhVtexShelf.salesChannel:"/api/catalog_system/pub/products/search?"+a+"&sc="+rhVtexShelf.salesChannel;
d.open("get",g,!0);d.onreadystatechange=function(){var a=function(){var a=JSON.parse(d.responseText);console.log("Produtos prateleira VTEX");console.log(a);rhVtexShelf.shelfs[b].vtexData=a;a.forEach(function(a){a.items.forEach(function(a){0<a.sellers[0].commertialOffer.AvailableQuantity&&(rhVtexShelf.products[a.itemId]=a)})});var c=rhVtexShelf.shelfs[b].container;rhVtexShelf.setPrices(c);rhVtexShelf.addVariantOptions(c,a);rhVtexShelf.setShelfListeners(c)};4==d.readyState&&206==d.status&&a();4==d.readyState&&
200==d.status&&a()};d.send(null)};rhVtexShelf.getAllProducts=function(){var a=0;rhVtexShelf.shelfs.forEach(function(b){if(0<=b.container.innerHTML.indexOf("{sale_price}")&&0<=b.container.innerHTML.indexOf("{old_price}"))rhVtexShelf.getProductsById(b.idList,a),a++;else{b=b.container.querySelectorAll(".rh-product");for(var c=0;c<b.length;c++)rhVtexShelf.bindActionsToProduct(b[c])}})};rhVtexShelf.addVariantOptions=function(a,b){var c=a.querySelectorAll(".rh-product");a=function(a){var d=c[a],e=d.dataset.rhId;
b.forEach(function(a){a.productId==e&&rhVtexShelf.addVariantOptionsToProduct(a,d)})};for(var d=0;d<c.length;d++)a(d)};rhVtexShelf.addVariantOptionsToProduct=function(a,b){a=a.items;var c=b.querySelector(".rh-variant-options"),f=!1,g=!1,h=d.createElement("select");h.classList="rh-color-option";h.dataset.rhVariationOption="color";var k=d.createElement("select");k.classList="rh-color-option";k.dataset.rhVariationOption="color";var l=document.createElement("option");l.selected="true";l.disabled="true";
l.innerHTML="Selecione";l.classList="rh-select-variation-label";h.appendChild(l);l=document.createElement("option");l.selected="true";l.disabled="true";l.innerHTML="Selecione";l.classList="rh-select-variation-label";k.appendChild(l);a.forEach(function(a){if(a.variations&&0<a.sellers[0].commertialOffer.AvailableQuantity){var c=rhVtexShelf.shelfs[b.dataset.rhShelf].cfg.options;a.variations.forEach(function(d){c.forEach(function(c){switch(c){case "color":if("cor"===d.toLowerCase()||"color"===d.toLowerCase()){c=
document.createElement("option");var e=a[d];c.value=a.itemId;c.innerHTML=e;c.dataset.rhColor=e;""!==b.dataset.rhSku&&a.itemId==b.dataset.rhSku&&(c.selected="true");h.appendChild(c);f=!0}break;case "size":if("tamanho"===d.toLowerCase()||"size"===d.toLowerCase())c=document.createElement("option"),e=a[d],c.value=a.itemId,c.innerHTML=e,c.dataset.rhColor=e,""!==b.dataset.rhSku&&a.itemId==b.dataset.rhSku&&(c.selected="true"),k.appendChild(c),g=!0}})})}});f&&(c.appendChild(h),h.addEventListener("change",
function(){rhVtexShelf.changeProduct(this.value,b)}));g&&(c.appendChild(k),k.addEventListener("change",function(){rhVtexShelf.changeProduct(this.value,b)}))};rhVtexShelf.changeProduct=function(a,b){var c=this.products[a],d=this.shelfs[b.dataset.rhShelf],g=d.productModel[b.dataset.rhId];g=rhVtexShelf.loadInfoToHtml(g,c);var h=document.createElement("ul");h.innerHTML=g;g=h.querySelector(".rh-product-info");b.querySelector(".rh-product-info").innerHTML=g.innerHTML;b.dataset.rhSku=a;b.dataset.rhAvailableQuantity=
c.sellers[0].commertialOffer.AvailableQuantity;if(d.container.querySelector(".rh-buy-together")){g=d.container.querySelectorAll(".rh-product");a=rhVtexShelf.products[g[0].dataset.rhSku];var k=rhVtexShelf.products[g[1].dataset.rhSku];a&&k&&(g=a.sellers[0].commertialOffer.ListPrice>=a.sellers[0].commertialOffer.Price?a.sellers[0].commertialOffer.ListPrice:a.sellers[0].commertialOffer.Price,h=k.sellers[0].commertialOffer.ListPrice>=k.sellers[0].commertialOffer.Price?k.sellers[0].commertialOffer.ListPrice:
k.sellers[0].commertialOffer.Price,a=this.util.toReais((a.sellers[0].commertialOffer.ListPrice<=a.sellers[0].commertialOffer.Price?a.sellers[0].commertialOffer.ListPrice:a.sellers[0].commertialOffer.Price)+(k.sellers[0].commertialOffer.ListPrice<=k.sellers[0].commertialOffer.Price?k.sellers[0].commertialOffer.ListPrice:k.sellers[0].commertialOffer.Price)),g=this.util.toReais(g+h),h=d.container.querySelector(".rh-buy-together"),d=h.querySelector(".rh-buy-together-new-price"),h=h.querySelector(".rh-buy-together-old-price"),
d&&(d.innerHTML=a),h&&(h.innerHTML=g),a==g?h&&(h.parentElement.style.display="none"):h&&(h.parentElement.style.display="block"))}b.querySelector(".rh-product-image").src=c.images[0].imageUrl;if(b=b.querySelector(".rh-qtt-input"))b.value=1};rhVtexShelf.unmarkColorButtons=function(a){a=a.querySelectorAll(".rh-color-option-button");for(var b=0;b<a.length;b++)a[b].classList.remove("rh-active")};rhVtexShelf.setShelfListeners=function(a){for(var b=a.querySelectorAll(".rh-product"),c=0;c<b.length;c++)this.bindActionsToProduct(b[c]);
if(b=a.querySelector(".rh-add-to-cart-cj-2")){var d=a.querySelector(".rh-buy-together");b.addEventListener("click",function(){var b=a.querySelectorAll(".rh-product")[0],c=a.querySelectorAll(".rh-product")[1],e=b.dataset.rhSku,f=c.dataset.rhSku;if(""!==e&&""!==f){b=b.querySelector(".rh-qtt-input");var m=c.querySelector(".rh-qtt-input");b?(b=b.value,m=m.value):m=b=1;rhVtexShelf.addToCart(e,b);setTimeout(function(){rhVtexShelf.addToCart(f,m)},500);d.classList.add("rh-success");setTimeout(function(){d.classList.remove("rh-success")},
2E3)}else d.classList.add("rh-error"),setTimeout(function(){d.classList.remove("rh-error")},2E3)})}};rhVtexShelf.bindActionsToProduct=function(a){var b=a.dataset.rhSku,c=parseInt(a.dataset.rhAvailableQuantity),d=a.querySelector(".rh-add-button"),g=a.querySelector(".rh-qtt-input"),h=a.querySelector(".rh-decrease-qtt"),k=a.querySelector(".rh-increase-qtt"),l=parseInt(a.dataset.rhShelf),m=rhVtexShelf.shelfs[l].container;k.dataset.rhSku=b;h.dataset.rhSku=b;g.dataset.rhSku=b;d.dataset.rhSku=b;d.addEventListener("click",
function(){var b=g.value,c=a.dataset.rhSku;""===c?(a.classList.add("rh-error"),setTimeout(function(){a.classList.remove("rh-error")},2E3)):(a.classList.add("rh-success"),rhVtexShelf.addToCart(c,b),setTimeout(function(){a.classList.remove("rh-success")},2E3))});g.addEventListener("keyup",function(){var a=product.availableQuantity,b=parseInt(this.value.replace(/[^0-9\.]/g,"").trim());b>a&&(b=a);productOldPrice&&(oldPrice=roiHeroComponents.util.BRLToFloat(productOldPrice.innerHTML),oldPrice/=b);this.value=
b;productNewPrice&&(productNewPrice.innerHTML=roiHeroComponents.util.numberToBRL(product.sellers[0].commertialOffer.Price*b));productOldPrice&&(productOldPrice.innerHTML=roiHeroComponents.util.numberToBRL(product.sellers[0].commertialOffer.ListPrice*b))});k.addEventListener("click",function(){var b=parseInt(g.value),d=a.querySelector(".rh-product-new-price"),e=a.querySelector(".rh-product-old-price"),f=0,h=0;d&&(h=roiHeroComponents.util.BRLToFloat(d.innerHTML),h/=b);e&&(f=roiHeroComponents.util.BRLToFloat(e.innerHTML),
f/=b);b++;if(b>c)b=c;else{var k=m.querySelector(".rh-buy-together-new-price");if(k){var l=roiHeroComponents.util.BRLToFloat(k.innerHTML);k.innerHTML=roiHeroComponents.util.numberToBRL(l-h*(b-1)+h*b)}if(k=m.querySelector(".rh-buy-together-new-price"))l=roiHeroComponents.util.BRLToFloat(k.innerHTML),k.innerHTML=roiHeroComponents.util.numberToBRL(l-f*(b-1)+f*b)}g.value=b;d&&(d.innerHTML=roiHeroComponents.util.numberToBRL(h*b));e&&(e.innerHTML=roiHeroComponents.util.numberToBRL(f*b))});h.addEventListener("click",
function(){var b=parseInt(g.value),c=a.querySelector(".rh-product-new-price"),d=a.querySelector(".rh-product-old-price"),e=0,f=0;c&&(f=roiHeroComponents.util.BRLToFloat(c.innerHTML),f/=b);d&&(e=roiHeroComponents.util.BRLToFloat(d.innerHTML),e/=b);b--;if(0>=b||isNaN(b))b=1;else{var h=m.querySelector(".rh-buy-together-new-price");if(h){var k=roiHeroComponents.util.BRLToFloat(h.innerHTML);h.innerHTML=roiHeroComponents.util.numberToBRL(k-f)}if(h=m.querySelector(".rh-buy-together-new-price"))k=roiHeroComponents.util.BRLToFloat(h.innerHTML),
h.innerHTML=roiHeroComponents.util.numberToBRL(k-e)}g.value=b;c&&(c.innerHTML=roiHeroComponents.util.numberToBRL(f*b));d&&(d.innerHTML=roiHeroComponents.util.numberToBRL(e*b))});b=a.querySelectorAll(".rh-color-option-button");for(d=0;d<b.length;d++)b[d].addEventListener("click",function(){var b=this.dataset.rhColorSku;rhVtexShelf.unmarkColorButtons(a);this.classList.add("rh-active");rhVtexShelf.changeProductVariation(b,a)})};rhVtexShelf.addToCart=function(a,b){if(0<Object.keys(rhVtexShelf.products).length){a=
rhVtexShelf.products[a].sellers[0].addToCartLink;a=a.replace("&qty=1","&qty="+(b||1));var c=new XMLHttpRequest;c.open("get",a,!0);c.onreadystatechange=function(){if(4==c.readyState&&200==c.status||302==c.status)if(rhVtexShelf.config.addToCartAditionalScript&&rhVtexShelf.config.addToCartAditionalScript(),"undefined"!==typeof vtexjs)try{vtexjs.checkout.getOrderForm()}catch(g){}};c.send(null)}else{var d=new XMLHttpRequest;d.open("get","/checkout/cart/add?sku="+a+"&qty="+b+"&seller=1&redirect=true&sc="+
rhVtexShelf.salesChannel,!0);d.onreadystatechange=function(){if(4==d.readyState&&200==d.status||302==d.status)if(rhVtexShelf.config.addToCartAditionalScript&&rhVtexShelf.config.addToCartAditionalScript(),"undefined"!==typeof vtexjs)try{vtexjs.checkout.getOrderForm()}catch(g){}};d.send(null)}};rhVtexShelf.getProductsForStaples=function(a,b){var c=a.length-1,d=new XMLHttpRequest;a="fq=skuId:"+a.join("&fq=skuId:");var g="";g=10<c?"/api/catalog_system/pub/products/search?"+a+"&_from=0&_to="+c+"&sc="+
rhVtexShelf.salesChannel:"/api/catalog_system/pub/products/search?"+a+"&sc="+rhVtexShelf.salesChannel;d.open("get",g,!0);d.onreadystatechange=function(){var a=function(){var a=JSON.parse(d.responseText);console.log("Produtos prateleira VTEX");console.log(a);rhVtexShelf.shelfs[b].vtexData=a;a.forEach(function(a){a.items.forEach(function(a){rhVtexShelf.products[a.itemId]=a})});var c=rhVtexShelf.shelfs[b].container;rhVtexShelf.setPrices(c);rhVtexShelf.addColorOptions(c,a);rhVtexShelf.setShelfListeners(c)};
4==d.readyState&&206==d.status&&a();4==d.readyState&&200==d.status&&a()};d.send(null)};rhVtexShelf.addColorOptions=function(a,b){var c=a.querySelectorAll(".rh-product");a=function(a){var e=c[a],f=e.dataset.rhId,g=e.dataset.rhSku;a=e.querySelector(".rh-color-options");var m=[],v=d.createElement("div");b.forEach(function(a){if(a.productId==f){a.items.forEach(function(a){if(a.Cor){var b=a.Cor[0];a=a.itemId;var c=d.createElement("span");c.dataset.rhColorSku=a;c.classList="rh-color-option-button "+b;g==
a&&c.classList.add("rh-active");m.push(c)}});a=a.productName.toLowerCase();var b=e.querySelector(".rh-product-image-container");-1!=a.indexOf("papel")&&-1!=a.indexOf("a0")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a0">A0</span>');-1!=a.indexOf("papel")&&-1!=a.indexOf("a1")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a1">A1</span>');-1!=a.indexOf("papel")&&-1!=a.indexOf("a2")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a2">A2</span>');
-1!=a.indexOf("papel")&&-1!=a.indexOf("a3")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a3">A3</span>');-1!=a.indexOf("papel")&&-1!=a.indexOf("a4")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a4">A4</span>');-1!=a.indexOf("papel")&&-1!=a.indexOf("a5")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--a5">A5</span>');-1!=a.indexOf("papel")&&-1!=a.indexOf("carta")&&(b.innerHTML+='<span class="x-image__highlight x-image__highlight--carta">Carta</span>')}});
m.forEach(function(a){v.appendChild(a)});a.appendChild(v)};for(var f=0;f<c.length;f++)a(f)};rhVtexShelf.getAllProductsForStaples=function(){var a=0;rhVtexShelf.shelfs.forEach(function(b){rhVtexShelf.getProductsForStaples(b.skuList,a);a++})};rhVtexShelf.changeProductVariation=function(a,b){b.dataset.rhSku=a;for(var c=b.querySelectorAll("[data-rh-sku]"),d=0;d<c.length;d++)c[d].dataset.rhSku=a;d=b.querySelector(".rh-product-image");c=rhVtexShelf.products[a];d.src=c.images[0].imageUrl;d=b.querySelector(".rh-product-old-price");
var g=b.querySelector(".rh-product-new-price");a=b.querySelector(".rh-installment-value");b=b.querySelector(".rh-installment-times");var h=this.util.toReais(c.sellers[0].commertialOffer.ListPrice),k=this.util.toReais(c.sellers[0].commertialOffer.Price);d&&(d.innerHTML=h);g&&(g.innerHTML=k);if(a&&b){c=c.sellers[0].commertialOffer.Installments;h=g=d=0;if(0<c.length){for(g=0;g<c.length;g++)1<c[g].NumberOfInstallments&&(d=g);g=c[d].NumberOfInstallments;h=rhVtexShelf.util.toReais(c[d].Value)}a.innerHTML=
h;b.innerHTML=g}};rhVtexShelf.init()})(window,document);
var bazarHorizonte={loadProds:function(){for(var c=document.querySelectorAll(".rh-product.rh-bh"),d=0;d<c.length;d++){var a=c[d],b=a.dataset.rhSku,e=a.querySelector(".rh-buy-button .rh-product-link"),f=a.querySelector(".rh-x-qtt");1<b.split(",").length?(e.style.display="block",f.style.display="none"):(e.style.display="none",f.style.display="block",bazarHorizonte.addListeners(a))}c=document.querySelectorAll(".rh-product.rh-bh-cc");for(d=0;d<c.length;d++)bazarHorizonte.addListenersVS(c[d]);c=document.querySelectorAll(".rh-bh-shelf");
for(d=0;d<c.length;d++){a=c[d];b=a.querySelectorAll(".rh-product");e=[];for(f=0;f<b.length;f++)e.push(b[f].dataset.rhSku),20===f&&(bazarHorizonte.getProds(e,a),e=[]);bazarHorizonte.getProds(e,a)}},getProds:function(c,d){var a="/api/catalog_system/pub/products/search?fq=skuId:"+c.join("&fq=skuId:");10<c.length&&(a+="&_from=0&_to="+(c.length-1));var b=new XMLHttpRequest;b.open("get",a,!0);b.onreadystatechange=function(){if(4==b.readyState){var a=JSON.parse(b.responseText);console.log(a);a.forEach(function(a){var b=
d.querySelectorAll('.rh-product[data-rh-id="'+a.productId+'"]');if(b)for(var c=0;c<b.length;c++){var e=b[c],f=e.querySelector(".rh-buy-button .rh-product-link");e=e.querySelector(".rh-x-qtt");1<a.items.length?(f.style.display="block",e.style.display="none"):(f.style.display="none",e.style.display="block")}else console.log("document.querySelectorAll('.rh-product[data-rh-id=\"'+prod.productId+'\"]')")})}};b.send(null)},addListeners:function(c){var d=c.querySelector(".rh-qtt-input"),a=c.querySelector(".rh-add-button"),
b=c.querySelector(".rh-increase-qtt"),e=c.querySelector(".rh-decrease-qtt"),f=c.dataset.rhSku.split(",")[0];a.addEventListener("click",function(){bazarHorizonte.addToCart(f,d.value)});d.addEventListener("keyup",function(){var a=d.value;isNaN(a)&&(a=1);1>a&&(a=1);100<a&&(a=100);d.value=a});b.addEventListener("click",function(){var a=d.value;a++;100<a&&(a=100);d.value=a});e.addEventListener("click",function(){var a=d.value;a--;1>a&&(a=1);d.value=a})},addListenersVS:function(c){var d=c.querySelector(".rh-qtt-input");
c.querySelector(".rh-add-button-cc").addEventListener("click",function(){var a=c.dataset.rhSku.split(",")[0];""===a?c.querySelector(".rh-warning-message").style.display="block":bazarHorizonte.addToCart(a,d.value)})},addToCart:function(c,d){vtexjs.checkout.addToCart([{id:c,quantity:d,seller:1}]).done(function(a){var b=document.querySelector('.rh-product[data-rh-sku="'+c+'"');a=0<a.messages.length?'<div class="show-action-success" style="background: aliceblue; padding: 5px; border-radius: 10px; position: absolute; top: 20px; height: 300px; border: 1px solid orange;"><div style="padding:5px;height: auto;"><p id="erro-quantidade" style="display: block; font-size: 10px; color: black; text-align: center; background: lightyellow; border: 0.5px dashed darkgoldenrod; padding: 5px;"><img src="https://bazarhorizonte.vteximg.com.br/arquivos/notificacao.png"><br>Ops, n\u00e3o temos a quantidade desse produto que voc\u00ea solicitou. Confira a quantidade que separamos para voc\u00ea no carrinho de compras.</p><p>O que voc\u00ea deseja fazer?</p><a onmouseover="this.style.background=\'rgb(107, 183, 107)\';this.style.textDecoration=\'none\'" onmouseout="this.style.background=\'#8dc63f\'" href="/Site/Carrinho.aspx" style="display:block;padding: 10px 30px 11px;border: none;border-radius: 4px;background: #8dc63f;font-size: 15px;color: #fff;">FINALIZAR PEDIDO</a><a class="btn-continuar-comprando-44354" onmouseover="this.style.textDecoration=\'none\'" href="javascript:void(0)" style="display:block;padding: 10px 30px 11px;border: none;border-radius: 4px;background: #CCC;font-size: 15px;color: white;margin-top: 5px;" onclick="this.parentElement.parentElement.outerHTML = \'\'" >CONTINUAR COMPRANDO</a></div></div>':
'<div class="show-action-success" style="background: aliceblue; padding: 5px; border-radius: 10px; position: absolute; top: 20px; height: 300px; border: 1px solid orange;"><div style="padding:5px;height: auto;"><p>O que voc\u00ea deseja fazer?</p><a onmouseover="this.style.background=\'rgb(107, 183, 107)\';this.style.textDecoration=\'none\'" onmouseout="this.style.background=\'#8dc63f\'" href="/Site/Carrinho.aspx" style="display:block;padding: 10px 30px 11px;border: none;border-radius: 4px;background: #8dc63f;font-size: 15px;color: #fff;">FINALIZAR PEDIDO</a><a class="btn-continuar-comprando-44354" onmouseover="this.style.textDecoration=\'none\'" href="javascript:void(0)" style="display:block;padding: 10px 30px 11px;border: none;border-radius: 4px;background: #CCC;font-size: 15px;color: white;margin-top: 5px;" onclick="this.parentElement.parentElement.outerHTML = \'\'" >CONTINUAR COMPRANDO</a></div></div>';
var d=document.createElement("div");d.innerHTML=a;b.appendChild(d.firstChild)})},init:function(){bazarHorizonte.loadProds()}};bazarHorizonte.init();
